name: setup-cached-python-client

inputs:
  version:
    description: Which Python version to install
    required: true
    default: "3.10"
  working-directory:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
      with:
        python-version: ${{ inputs.version }}

    - name: Setup uv with caching
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      with:
        enable-cache: true
        version: "0.9.24"
        activate-environment: "true"
        cache-dependency-glob: |
          ${{ inputs.working-directory }}/requirements.dev.txt
          ${{ inputs.working-directory }}/pyproject.toml

    - name: Install Python packages
      shell: bash
      run: |
        uv pip install -r requirements.dev.txt
      working-directory: ${{ inputs.working-directory }}
