# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: modal_proto/api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client

if typing.TYPE_CHECKING:
    import grpclib.server

import modal_proto.options_pb2
import google.protobuf.empty_pb2
import google.protobuf.wrappers_pb2
import modal_proto.api_pb2


class ModalClientBase(abc.ABC):
    @abc.abstractmethod
    async def AppCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.AppCreateRequest, modal_proto.api_pb2.AppCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def AppClientDisconnect(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.AppClientDisconnectRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def AppGetLogs(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.AppGetLogsRequest, modal_proto.api_pb2.TaskLogsBatch]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def AppSetObjects(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.AppSetObjectsRequest, google.protobuf.empty_pb2.Empty]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def AppGetObjects(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.AppGetObjectsRequest, modal_proto.api_pb2.AppGetObjectsResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def AppList(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.AppListRequest, modal_proto.api_pb2.AppListResponse]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def AppLookupObject(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.AppLookupObjectRequest, modal_proto.api_pb2.AppLookupObjectResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def AppDeploy(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.AppDeployRequest, modal_proto.api_pb2.AppDeployResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def AppDeploySingleObject(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.AppDeploySingleObjectRequest, modal_proto.api_pb2.AppDeploySingleObjectResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def AppGetByDeploymentName(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.AppGetByDeploymentNameRequest, modal_proto.api_pb2.AppGetByDeploymentNameResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def AppStop(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.AppStopRequest, google.protobuf.empty_pb2.Empty]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def AppHeartbeat(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.AppHeartbeatRequest, google.protobuf.empty_pb2.Empty]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def BlobCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.BlobCreateRequest, modal_proto.api_pb2.BlobCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def BlobGet(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.BlobGetRequest, modal_proto.api_pb2.BlobGetResponse]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def ClassCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.ClassCreateRequest, modal_proto.api_pb2.ClassCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ClassGet(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.ClassGetRequest, modal_proto.api_pb2.ClassGetResponse]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def ClientCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.ClientCreateRequest, modal_proto.api_pb2.ClientCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ClientHello(
        self, stream: "grpclib.server.Stream[google.protobuf.empty_pb2.Empty, modal_proto.api_pb2.ClientHelloResponse]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def ClientHeartbeat(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.ClientHeartbeatRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ContainerHeartbeat(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.ContainerHeartbeatRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ContainerCheckpoint(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.ContainerCheckpointRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def DictClear(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.DictClearRequest, google.protobuf.empty_pb2.Empty]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def DictCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.DictCreateRequest, modal_proto.api_pb2.DictCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def DictUpdate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.DictUpdateRequest, modal_proto.api_pb2.DictUpdateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def DictGet(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.DictGetRequest, modal_proto.api_pb2.DictGetResponse]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def DictPop(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.DictPopRequest, modal_proto.api_pb2.DictPopResponse]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def DictContains(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.DictContainsRequest, modal_proto.api_pb2.DictContainsResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def DictLen(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.DictLenRequest, modal_proto.api_pb2.DictLenResponse]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def DomainCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.DomainCreateRequest, modal_proto.api_pb2.DomainCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def DomainList(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.DomainListRequest, modal_proto.api_pb2.DomainListResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def DomainCertificateVerify(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.DomainCertificateVerifyRequest, modal_proto.api_pb2.DomainCertificateVerifyResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def EnvironmentCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.EnvironmentCreateRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def EnvironmentList(
        self,
        stream: "grpclib.server.Stream[google.protobuf.empty_pb2.Empty, modal_proto.api_pb2.EnvironmentListResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def EnvironmentDelete(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.EnvironmentDeleteRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def EnvironmentUpdate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.EnvironmentUpdateRequest, modal_proto.api_pb2.EnvironmentListItem]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionBindParams(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionBindParamsRequest, modal_proto.api_pb2.FunctionBindParamsResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionCreateRequest, modal_proto.api_pb2.FunctionCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionGet(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionGetRequest, modal_proto.api_pb2.FunctionGetResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionGetCallGraph(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionGetCallGraphRequest, modal_proto.api_pb2.FunctionGetCallGraphResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionGetCurrentStats(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionGetCurrentStatsRequest, modal_proto.api_pb2.FunctionStats]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionGetInputs(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionGetInputsRequest, modal_proto.api_pb2.FunctionGetInputsResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionGetOutputs(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionGetOutputsRequest, modal_proto.api_pb2.FunctionGetOutputsResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionGetSerialized(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionGetSerializedRequest, modal_proto.api_pb2.FunctionGetSerializedResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionMap(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionMapRequest, modal_proto.api_pb2.FunctionMapResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionPrecreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionPrecreateRequest, modal_proto.api_pb2.FunctionPrecreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionPutInputs(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionPutInputsRequest, modal_proto.api_pb2.FunctionPutInputsResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionPutOutputs(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionPutOutputsRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionCallCancel(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionCallCancelRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionCallList(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionCallListRequest, modal_proto.api_pb2.FunctionCallListResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionCallGetDataIn(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionCallGetDataRequest, modal_proto.api_pb2.DataChunk]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def FunctionCallPutDataOut(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.FunctionCallPutDataRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ImageGetOrCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.ImageGetOrCreateRequest, modal_proto.api_pb2.ImageGetOrCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ImageJoinStreaming(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.ImageJoinStreamingRequest, modal_proto.api_pb2.ImageJoinStreamingResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def MountPutFile(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.MountPutFileRequest, modal_proto.api_pb2.MountPutFileResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def MountBuild(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.MountBuildRequest, modal_proto.api_pb2.MountBuildResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def QueueCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.QueueCreateRequest, modal_proto.api_pb2.QueueCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def QueueGet(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.QueueGetRequest, modal_proto.api_pb2.QueueGetResponse]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def QueuePut(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.QueuePutRequest, google.protobuf.empty_pb2.Empty]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def QueueLen(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.QueueLenRequest, modal_proto.api_pb2.QueueLenResponse]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def SandboxCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SandboxCreateRequest, modal_proto.api_pb2.SandboxCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SandboxGetLogs(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SandboxGetLogsRequest, modal_proto.api_pb2.TaskLogsBatch]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SandboxWait(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SandboxWaitRequest, modal_proto.api_pb2.SandboxWaitResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SandboxList(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SandboxListRequest, modal_proto.api_pb2.SandboxListResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SandboxTerminate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SandboxTerminateRequest, modal_proto.api_pb2.SandboxTerminateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SecretCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SecretCreateRequest, modal_proto.api_pb2.SecretCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SecretList(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SecretListRequest, modal_proto.api_pb2.SecretListResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SharedVolumeCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SharedVolumeCreateRequest, modal_proto.api_pb2.SharedVolumeCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SharedVolumeList(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SharedVolumeListRequest, modal_proto.api_pb2.SharedVolumeListResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SharedVolumeListFiles(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SharedVolumeListFilesRequest, modal_proto.api_pb2.SharedVolumeListFilesResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SharedVolumeListFilesStream(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SharedVolumeListFilesRequest, modal_proto.api_pb2.SharedVolumeListFilesResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SharedVolumePutFile(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SharedVolumePutFileRequest, modal_proto.api_pb2.SharedVolumePutFileResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SharedVolumeGetFile(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SharedVolumeGetFileRequest, modal_proto.api_pb2.SharedVolumeGetFileResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SharedVolumeRemoveFile(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.SharedVolumeRemoveFileRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def TaskResult(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.TaskResultRequest, google.protobuf.empty_pb2.Empty]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def TaskList(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.TaskListRequest, modal_proto.api_pb2.TaskListResponse]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def TokenFlowCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.TokenFlowCreateRequest, modal_proto.api_pb2.TokenFlowCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def TokenFlowWait(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.TokenFlowWaitRequest, modal_proto.api_pb2.TokenFlowWaitResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def TunnelStart(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.TunnelStartRequest, modal_proto.api_pb2.TunnelStartResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def TunnelStop(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.TunnelStopRequest, modal_proto.api_pb2.TunnelStopResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def VolumeCreate(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.VolumeCreateRequest, modal_proto.api_pb2.VolumeCreateResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def VolumeCommit(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.VolumeCommitRequest, modal_proto.api_pb2.VolumeCommitResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def VolumeGetFile(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.VolumeGetFileRequest, modal_proto.api_pb2.VolumeGetFileResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def VolumeList(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.VolumeListRequest, modal_proto.api_pb2.VolumeListResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def VolumeListFiles(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.VolumeListFilesRequest, modal_proto.api_pb2.VolumeListFilesResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def VolumePutFiles(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.VolumePutFilesRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def VolumeReload(
        self, stream: "grpclib.server.Stream[modal_proto.api_pb2.VolumeReloadRequest, google.protobuf.empty_pb2.Empty]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def VolumeRemoveFile(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.VolumeRemoveFileRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def VolumeCopyFiles(
        self,
        stream: "grpclib.server.Stream[modal_proto.api_pb2.VolumeCopyFilesRequest, google.protobuf.empty_pb2.Empty]",
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            "/modal.client.ModalClient/AppCreate": grpclib.const.Handler(
                self.AppCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.AppCreateRequest,
                modal_proto.api_pb2.AppCreateResponse,
            ),
            "/modal.client.ModalClient/AppClientDisconnect": grpclib.const.Handler(
                self.AppClientDisconnect,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.AppClientDisconnectRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/AppGetLogs": grpclib.const.Handler(
                self.AppGetLogs,
                grpclib.const.Cardinality.UNARY_STREAM,
                modal_proto.api_pb2.AppGetLogsRequest,
                modal_proto.api_pb2.TaskLogsBatch,
            ),
            "/modal.client.ModalClient/AppSetObjects": grpclib.const.Handler(
                self.AppSetObjects,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.AppSetObjectsRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/AppGetObjects": grpclib.const.Handler(
                self.AppGetObjects,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.AppGetObjectsRequest,
                modal_proto.api_pb2.AppGetObjectsResponse,
            ),
            "/modal.client.ModalClient/AppList": grpclib.const.Handler(
                self.AppList,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.AppListRequest,
                modal_proto.api_pb2.AppListResponse,
            ),
            "/modal.client.ModalClient/AppLookupObject": grpclib.const.Handler(
                self.AppLookupObject,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.AppLookupObjectRequest,
                modal_proto.api_pb2.AppLookupObjectResponse,
            ),
            "/modal.client.ModalClient/AppDeploy": grpclib.const.Handler(
                self.AppDeploy,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.AppDeployRequest,
                modal_proto.api_pb2.AppDeployResponse,
            ),
            "/modal.client.ModalClient/AppDeploySingleObject": grpclib.const.Handler(
                self.AppDeploySingleObject,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.AppDeploySingleObjectRequest,
                modal_proto.api_pb2.AppDeploySingleObjectResponse,
            ),
            "/modal.client.ModalClient/AppGetByDeploymentName": grpclib.const.Handler(
                self.AppGetByDeploymentName,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.AppGetByDeploymentNameRequest,
                modal_proto.api_pb2.AppGetByDeploymentNameResponse,
            ),
            "/modal.client.ModalClient/AppStop": grpclib.const.Handler(
                self.AppStop,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.AppStopRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/AppHeartbeat": grpclib.const.Handler(
                self.AppHeartbeat,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.AppHeartbeatRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/BlobCreate": grpclib.const.Handler(
                self.BlobCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.BlobCreateRequest,
                modal_proto.api_pb2.BlobCreateResponse,
            ),
            "/modal.client.ModalClient/BlobGet": grpclib.const.Handler(
                self.BlobGet,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.BlobGetRequest,
                modal_proto.api_pb2.BlobGetResponse,
            ),
            "/modal.client.ModalClient/ClassCreate": grpclib.const.Handler(
                self.ClassCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.ClassCreateRequest,
                modal_proto.api_pb2.ClassCreateResponse,
            ),
            "/modal.client.ModalClient/ClassGet": grpclib.const.Handler(
                self.ClassGet,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.ClassGetRequest,
                modal_proto.api_pb2.ClassGetResponse,
            ),
            "/modal.client.ModalClient/ClientCreate": grpclib.const.Handler(
                self.ClientCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.ClientCreateRequest,
                modal_proto.api_pb2.ClientCreateResponse,
            ),
            "/modal.client.ModalClient/ClientHello": grpclib.const.Handler(
                self.ClientHello,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                modal_proto.api_pb2.ClientHelloResponse,
            ),
            "/modal.client.ModalClient/ClientHeartbeat": grpclib.const.Handler(
                self.ClientHeartbeat,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.ClientHeartbeatRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/ContainerHeartbeat": grpclib.const.Handler(
                self.ContainerHeartbeat,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.ContainerHeartbeatRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/ContainerCheckpoint": grpclib.const.Handler(
                self.ContainerCheckpoint,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.ContainerCheckpointRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/DictClear": grpclib.const.Handler(
                self.DictClear,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.DictClearRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/DictCreate": grpclib.const.Handler(
                self.DictCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.DictCreateRequest,
                modal_proto.api_pb2.DictCreateResponse,
            ),
            "/modal.client.ModalClient/DictUpdate": grpclib.const.Handler(
                self.DictUpdate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.DictUpdateRequest,
                modal_proto.api_pb2.DictUpdateResponse,
            ),
            "/modal.client.ModalClient/DictGet": grpclib.const.Handler(
                self.DictGet,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.DictGetRequest,
                modal_proto.api_pb2.DictGetResponse,
            ),
            "/modal.client.ModalClient/DictPop": grpclib.const.Handler(
                self.DictPop,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.DictPopRequest,
                modal_proto.api_pb2.DictPopResponse,
            ),
            "/modal.client.ModalClient/DictContains": grpclib.const.Handler(
                self.DictContains,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.DictContainsRequest,
                modal_proto.api_pb2.DictContainsResponse,
            ),
            "/modal.client.ModalClient/DictLen": grpclib.const.Handler(
                self.DictLen,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.DictLenRequest,
                modal_proto.api_pb2.DictLenResponse,
            ),
            "/modal.client.ModalClient/DomainCreate": grpclib.const.Handler(
                self.DomainCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.DomainCreateRequest,
                modal_proto.api_pb2.DomainCreateResponse,
            ),
            "/modal.client.ModalClient/DomainList": grpclib.const.Handler(
                self.DomainList,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.DomainListRequest,
                modal_proto.api_pb2.DomainListResponse,
            ),
            "/modal.client.ModalClient/DomainCertificateVerify": grpclib.const.Handler(
                self.DomainCertificateVerify,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.DomainCertificateVerifyRequest,
                modal_proto.api_pb2.DomainCertificateVerifyResponse,
            ),
            "/modal.client.ModalClient/EnvironmentCreate": grpclib.const.Handler(
                self.EnvironmentCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.EnvironmentCreateRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/EnvironmentList": grpclib.const.Handler(
                self.EnvironmentList,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                modal_proto.api_pb2.EnvironmentListResponse,
            ),
            "/modal.client.ModalClient/EnvironmentDelete": grpclib.const.Handler(
                self.EnvironmentDelete,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.EnvironmentDeleteRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/EnvironmentUpdate": grpclib.const.Handler(
                self.EnvironmentUpdate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.EnvironmentUpdateRequest,
                modal_proto.api_pb2.EnvironmentListItem,
            ),
            "/modal.client.ModalClient/FunctionBindParams": grpclib.const.Handler(
                self.FunctionBindParams,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionBindParamsRequest,
                modal_proto.api_pb2.FunctionBindParamsResponse,
            ),
            "/modal.client.ModalClient/FunctionCreate": grpclib.const.Handler(
                self.FunctionCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionCreateRequest,
                modal_proto.api_pb2.FunctionCreateResponse,
            ),
            "/modal.client.ModalClient/FunctionGet": grpclib.const.Handler(
                self.FunctionGet,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionGetRequest,
                modal_proto.api_pb2.FunctionGetResponse,
            ),
            "/modal.client.ModalClient/FunctionGetCallGraph": grpclib.const.Handler(
                self.FunctionGetCallGraph,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionGetCallGraphRequest,
                modal_proto.api_pb2.FunctionGetCallGraphResponse,
            ),
            "/modal.client.ModalClient/FunctionGetCurrentStats": grpclib.const.Handler(
                self.FunctionGetCurrentStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionGetCurrentStatsRequest,
                modal_proto.api_pb2.FunctionStats,
            ),
            "/modal.client.ModalClient/FunctionGetInputs": grpclib.const.Handler(
                self.FunctionGetInputs,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionGetInputsRequest,
                modal_proto.api_pb2.FunctionGetInputsResponse,
            ),
            "/modal.client.ModalClient/FunctionGetOutputs": grpclib.const.Handler(
                self.FunctionGetOutputs,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionGetOutputsRequest,
                modal_proto.api_pb2.FunctionGetOutputsResponse,
            ),
            "/modal.client.ModalClient/FunctionGetSerialized": grpclib.const.Handler(
                self.FunctionGetSerialized,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionGetSerializedRequest,
                modal_proto.api_pb2.FunctionGetSerializedResponse,
            ),
            "/modal.client.ModalClient/FunctionMap": grpclib.const.Handler(
                self.FunctionMap,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionMapRequest,
                modal_proto.api_pb2.FunctionMapResponse,
            ),
            "/modal.client.ModalClient/FunctionPrecreate": grpclib.const.Handler(
                self.FunctionPrecreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionPrecreateRequest,
                modal_proto.api_pb2.FunctionPrecreateResponse,
            ),
            "/modal.client.ModalClient/FunctionPutInputs": grpclib.const.Handler(
                self.FunctionPutInputs,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionPutInputsRequest,
                modal_proto.api_pb2.FunctionPutInputsResponse,
            ),
            "/modal.client.ModalClient/FunctionPutOutputs": grpclib.const.Handler(
                self.FunctionPutOutputs,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionPutOutputsRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/FunctionCallCancel": grpclib.const.Handler(
                self.FunctionCallCancel,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionCallCancelRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/FunctionCallList": grpclib.const.Handler(
                self.FunctionCallList,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionCallListRequest,
                modal_proto.api_pb2.FunctionCallListResponse,
            ),
            "/modal.client.ModalClient/FunctionCallGetDataIn": grpclib.const.Handler(
                self.FunctionCallGetDataIn,
                grpclib.const.Cardinality.UNARY_STREAM,
                modal_proto.api_pb2.FunctionCallGetDataRequest,
                modal_proto.api_pb2.DataChunk,
            ),
            "/modal.client.ModalClient/FunctionCallPutDataOut": grpclib.const.Handler(
                self.FunctionCallPutDataOut,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.FunctionCallPutDataRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/ImageGetOrCreate": grpclib.const.Handler(
                self.ImageGetOrCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.ImageGetOrCreateRequest,
                modal_proto.api_pb2.ImageGetOrCreateResponse,
            ),
            "/modal.client.ModalClient/ImageJoinStreaming": grpclib.const.Handler(
                self.ImageJoinStreaming,
                grpclib.const.Cardinality.UNARY_STREAM,
                modal_proto.api_pb2.ImageJoinStreamingRequest,
                modal_proto.api_pb2.ImageJoinStreamingResponse,
            ),
            "/modal.client.ModalClient/MountPutFile": grpclib.const.Handler(
                self.MountPutFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.MountPutFileRequest,
                modal_proto.api_pb2.MountPutFileResponse,
            ),
            "/modal.client.ModalClient/MountBuild": grpclib.const.Handler(
                self.MountBuild,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.MountBuildRequest,
                modal_proto.api_pb2.MountBuildResponse,
            ),
            "/modal.client.ModalClient/QueueCreate": grpclib.const.Handler(
                self.QueueCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.QueueCreateRequest,
                modal_proto.api_pb2.QueueCreateResponse,
            ),
            "/modal.client.ModalClient/QueueGet": grpclib.const.Handler(
                self.QueueGet,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.QueueGetRequest,
                modal_proto.api_pb2.QueueGetResponse,
            ),
            "/modal.client.ModalClient/QueuePut": grpclib.const.Handler(
                self.QueuePut,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.QueuePutRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/QueueLen": grpclib.const.Handler(
                self.QueueLen,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.QueueLenRequest,
                modal_proto.api_pb2.QueueLenResponse,
            ),
            "/modal.client.ModalClient/SandboxCreate": grpclib.const.Handler(
                self.SandboxCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SandboxCreateRequest,
                modal_proto.api_pb2.SandboxCreateResponse,
            ),
            "/modal.client.ModalClient/SandboxGetLogs": grpclib.const.Handler(
                self.SandboxGetLogs,
                grpclib.const.Cardinality.UNARY_STREAM,
                modal_proto.api_pb2.SandboxGetLogsRequest,
                modal_proto.api_pb2.TaskLogsBatch,
            ),
            "/modal.client.ModalClient/SandboxWait": grpclib.const.Handler(
                self.SandboxWait,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SandboxWaitRequest,
                modal_proto.api_pb2.SandboxWaitResponse,
            ),
            "/modal.client.ModalClient/SandboxList": grpclib.const.Handler(
                self.SandboxList,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SandboxListRequest,
                modal_proto.api_pb2.SandboxListResponse,
            ),
            "/modal.client.ModalClient/SandboxTerminate": grpclib.const.Handler(
                self.SandboxTerminate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SandboxTerminateRequest,
                modal_proto.api_pb2.SandboxTerminateResponse,
            ),
            "/modal.client.ModalClient/SecretCreate": grpclib.const.Handler(
                self.SecretCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SecretCreateRequest,
                modal_proto.api_pb2.SecretCreateResponse,
            ),
            "/modal.client.ModalClient/SecretList": grpclib.const.Handler(
                self.SecretList,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SecretListRequest,
                modal_proto.api_pb2.SecretListResponse,
            ),
            "/modal.client.ModalClient/SharedVolumeCreate": grpclib.const.Handler(
                self.SharedVolumeCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SharedVolumeCreateRequest,
                modal_proto.api_pb2.SharedVolumeCreateResponse,
            ),
            "/modal.client.ModalClient/SharedVolumeList": grpclib.const.Handler(
                self.SharedVolumeList,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SharedVolumeListRequest,
                modal_proto.api_pb2.SharedVolumeListResponse,
            ),
            "/modal.client.ModalClient/SharedVolumeListFiles": grpclib.const.Handler(
                self.SharedVolumeListFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SharedVolumeListFilesRequest,
                modal_proto.api_pb2.SharedVolumeListFilesResponse,
            ),
            "/modal.client.ModalClient/SharedVolumeListFilesStream": grpclib.const.Handler(
                self.SharedVolumeListFilesStream,
                grpclib.const.Cardinality.UNARY_STREAM,
                modal_proto.api_pb2.SharedVolumeListFilesRequest,
                modal_proto.api_pb2.SharedVolumeListFilesResponse,
            ),
            "/modal.client.ModalClient/SharedVolumePutFile": grpclib.const.Handler(
                self.SharedVolumePutFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SharedVolumePutFileRequest,
                modal_proto.api_pb2.SharedVolumePutFileResponse,
            ),
            "/modal.client.ModalClient/SharedVolumeGetFile": grpclib.const.Handler(
                self.SharedVolumeGetFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SharedVolumeGetFileRequest,
                modal_proto.api_pb2.SharedVolumeGetFileResponse,
            ),
            "/modal.client.ModalClient/SharedVolumeRemoveFile": grpclib.const.Handler(
                self.SharedVolumeRemoveFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.SharedVolumeRemoveFileRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/TaskResult": grpclib.const.Handler(
                self.TaskResult,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.TaskResultRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/TaskList": grpclib.const.Handler(
                self.TaskList,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.TaskListRequest,
                modal_proto.api_pb2.TaskListResponse,
            ),
            "/modal.client.ModalClient/TokenFlowCreate": grpclib.const.Handler(
                self.TokenFlowCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.TokenFlowCreateRequest,
                modal_proto.api_pb2.TokenFlowCreateResponse,
            ),
            "/modal.client.ModalClient/TokenFlowWait": grpclib.const.Handler(
                self.TokenFlowWait,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.TokenFlowWaitRequest,
                modal_proto.api_pb2.TokenFlowWaitResponse,
            ),
            "/modal.client.ModalClient/TunnelStart": grpclib.const.Handler(
                self.TunnelStart,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.TunnelStartRequest,
                modal_proto.api_pb2.TunnelStartResponse,
            ),
            "/modal.client.ModalClient/TunnelStop": grpclib.const.Handler(
                self.TunnelStop,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.TunnelStopRequest,
                modal_proto.api_pb2.TunnelStopResponse,
            ),
            "/modal.client.ModalClient/VolumeCreate": grpclib.const.Handler(
                self.VolumeCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.VolumeCreateRequest,
                modal_proto.api_pb2.VolumeCreateResponse,
            ),
            "/modal.client.ModalClient/VolumeCommit": grpclib.const.Handler(
                self.VolumeCommit,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.VolumeCommitRequest,
                modal_proto.api_pb2.VolumeCommitResponse,
            ),
            "/modal.client.ModalClient/VolumeGetFile": grpclib.const.Handler(
                self.VolumeGetFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.VolumeGetFileRequest,
                modal_proto.api_pb2.VolumeGetFileResponse,
            ),
            "/modal.client.ModalClient/VolumeList": grpclib.const.Handler(
                self.VolumeList,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.VolumeListRequest,
                modal_proto.api_pb2.VolumeListResponse,
            ),
            "/modal.client.ModalClient/VolumeListFiles": grpclib.const.Handler(
                self.VolumeListFiles,
                grpclib.const.Cardinality.UNARY_STREAM,
                modal_proto.api_pb2.VolumeListFilesRequest,
                modal_proto.api_pb2.VolumeListFilesResponse,
            ),
            "/modal.client.ModalClient/VolumePutFiles": grpclib.const.Handler(
                self.VolumePutFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.VolumePutFilesRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/VolumeReload": grpclib.const.Handler(
                self.VolumeReload,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.VolumeReloadRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/VolumeRemoveFile": grpclib.const.Handler(
                self.VolumeRemoveFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.VolumeRemoveFileRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            "/modal.client.ModalClient/VolumeCopyFiles": grpclib.const.Handler(
                self.VolumeCopyFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                modal_proto.api_pb2.VolumeCopyFilesRequest,
                google.protobuf.empty_pb2.Empty,
            ),
        }


class ModalClientStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.AppCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/AppCreate",
            modal_proto.api_pb2.AppCreateRequest,
            modal_proto.api_pb2.AppCreateResponse,
        )
        self.AppClientDisconnect = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/AppClientDisconnect",
            modal_proto.api_pb2.AppClientDisconnectRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.AppGetLogs = grpclib.client.UnaryStreamMethod(
            channel,
            "/modal.client.ModalClient/AppGetLogs",
            modal_proto.api_pb2.AppGetLogsRequest,
            modal_proto.api_pb2.TaskLogsBatch,
        )
        self.AppSetObjects = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/AppSetObjects",
            modal_proto.api_pb2.AppSetObjectsRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.AppGetObjects = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/AppGetObjects",
            modal_proto.api_pb2.AppGetObjectsRequest,
            modal_proto.api_pb2.AppGetObjectsResponse,
        )
        self.AppList = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/AppList",
            modal_proto.api_pb2.AppListRequest,
            modal_proto.api_pb2.AppListResponse,
        )
        self.AppLookupObject = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/AppLookupObject",
            modal_proto.api_pb2.AppLookupObjectRequest,
            modal_proto.api_pb2.AppLookupObjectResponse,
        )
        self.AppDeploy = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/AppDeploy",
            modal_proto.api_pb2.AppDeployRequest,
            modal_proto.api_pb2.AppDeployResponse,
        )
        self.AppDeploySingleObject = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/AppDeploySingleObject",
            modal_proto.api_pb2.AppDeploySingleObjectRequest,
            modal_proto.api_pb2.AppDeploySingleObjectResponse,
        )
        self.AppGetByDeploymentName = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/AppGetByDeploymentName",
            modal_proto.api_pb2.AppGetByDeploymentNameRequest,
            modal_proto.api_pb2.AppGetByDeploymentNameResponse,
        )
        self.AppStop = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/AppStop",
            modal_proto.api_pb2.AppStopRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.AppHeartbeat = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/AppHeartbeat",
            modal_proto.api_pb2.AppHeartbeatRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.BlobCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/BlobCreate",
            modal_proto.api_pb2.BlobCreateRequest,
            modal_proto.api_pb2.BlobCreateResponse,
        )
        self.BlobGet = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/BlobGet",
            modal_proto.api_pb2.BlobGetRequest,
            modal_proto.api_pb2.BlobGetResponse,
        )
        self.ClassCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/ClassCreate",
            modal_proto.api_pb2.ClassCreateRequest,
            modal_proto.api_pb2.ClassCreateResponse,
        )
        self.ClassGet = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/ClassGet",
            modal_proto.api_pb2.ClassGetRequest,
            modal_proto.api_pb2.ClassGetResponse,
        )
        self.ClientCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/ClientCreate",
            modal_proto.api_pb2.ClientCreateRequest,
            modal_proto.api_pb2.ClientCreateResponse,
        )
        self.ClientHello = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/ClientHello",
            google.protobuf.empty_pb2.Empty,
            modal_proto.api_pb2.ClientHelloResponse,
        )
        self.ClientHeartbeat = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/ClientHeartbeat",
            modal_proto.api_pb2.ClientHeartbeatRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.ContainerHeartbeat = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/ContainerHeartbeat",
            modal_proto.api_pb2.ContainerHeartbeatRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.ContainerCheckpoint = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/ContainerCheckpoint",
            modal_proto.api_pb2.ContainerCheckpointRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.DictClear = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/DictClear",
            modal_proto.api_pb2.DictClearRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.DictCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/DictCreate",
            modal_proto.api_pb2.DictCreateRequest,
            modal_proto.api_pb2.DictCreateResponse,
        )
        self.DictUpdate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/DictUpdate",
            modal_proto.api_pb2.DictUpdateRequest,
            modal_proto.api_pb2.DictUpdateResponse,
        )
        self.DictGet = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/DictGet",
            modal_proto.api_pb2.DictGetRequest,
            modal_proto.api_pb2.DictGetResponse,
        )
        self.DictPop = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/DictPop",
            modal_proto.api_pb2.DictPopRequest,
            modal_proto.api_pb2.DictPopResponse,
        )
        self.DictContains = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/DictContains",
            modal_proto.api_pb2.DictContainsRequest,
            modal_proto.api_pb2.DictContainsResponse,
        )
        self.DictLen = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/DictLen",
            modal_proto.api_pb2.DictLenRequest,
            modal_proto.api_pb2.DictLenResponse,
        )
        self.DomainCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/DomainCreate",
            modal_proto.api_pb2.DomainCreateRequest,
            modal_proto.api_pb2.DomainCreateResponse,
        )
        self.DomainList = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/DomainList",
            modal_proto.api_pb2.DomainListRequest,
            modal_proto.api_pb2.DomainListResponse,
        )
        self.DomainCertificateVerify = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/DomainCertificateVerify",
            modal_proto.api_pb2.DomainCertificateVerifyRequest,
            modal_proto.api_pb2.DomainCertificateVerifyResponse,
        )
        self.EnvironmentCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/EnvironmentCreate",
            modal_proto.api_pb2.EnvironmentCreateRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.EnvironmentList = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/EnvironmentList",
            google.protobuf.empty_pb2.Empty,
            modal_proto.api_pb2.EnvironmentListResponse,
        )
        self.EnvironmentDelete = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/EnvironmentDelete",
            modal_proto.api_pb2.EnvironmentDeleteRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.EnvironmentUpdate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/EnvironmentUpdate",
            modal_proto.api_pb2.EnvironmentUpdateRequest,
            modal_proto.api_pb2.EnvironmentListItem,
        )
        self.FunctionBindParams = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionBindParams",
            modal_proto.api_pb2.FunctionBindParamsRequest,
            modal_proto.api_pb2.FunctionBindParamsResponse,
        )
        self.FunctionCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionCreate",
            modal_proto.api_pb2.FunctionCreateRequest,
            modal_proto.api_pb2.FunctionCreateResponse,
        )
        self.FunctionGet = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionGet",
            modal_proto.api_pb2.FunctionGetRequest,
            modal_proto.api_pb2.FunctionGetResponse,
        )
        self.FunctionGetCallGraph = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionGetCallGraph",
            modal_proto.api_pb2.FunctionGetCallGraphRequest,
            modal_proto.api_pb2.FunctionGetCallGraphResponse,
        )
        self.FunctionGetCurrentStats = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionGetCurrentStats",
            modal_proto.api_pb2.FunctionGetCurrentStatsRequest,
            modal_proto.api_pb2.FunctionStats,
        )
        self.FunctionGetInputs = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionGetInputs",
            modal_proto.api_pb2.FunctionGetInputsRequest,
            modal_proto.api_pb2.FunctionGetInputsResponse,
        )
        self.FunctionGetOutputs = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionGetOutputs",
            modal_proto.api_pb2.FunctionGetOutputsRequest,
            modal_proto.api_pb2.FunctionGetOutputsResponse,
        )
        self.FunctionGetSerialized = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionGetSerialized",
            modal_proto.api_pb2.FunctionGetSerializedRequest,
            modal_proto.api_pb2.FunctionGetSerializedResponse,
        )
        self.FunctionMap = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionMap",
            modal_proto.api_pb2.FunctionMapRequest,
            modal_proto.api_pb2.FunctionMapResponse,
        )
        self.FunctionPrecreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionPrecreate",
            modal_proto.api_pb2.FunctionPrecreateRequest,
            modal_proto.api_pb2.FunctionPrecreateResponse,
        )
        self.FunctionPutInputs = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionPutInputs",
            modal_proto.api_pb2.FunctionPutInputsRequest,
            modal_proto.api_pb2.FunctionPutInputsResponse,
        )
        self.FunctionPutOutputs = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionPutOutputs",
            modal_proto.api_pb2.FunctionPutOutputsRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.FunctionCallCancel = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionCallCancel",
            modal_proto.api_pb2.FunctionCallCancelRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.FunctionCallList = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionCallList",
            modal_proto.api_pb2.FunctionCallListRequest,
            modal_proto.api_pb2.FunctionCallListResponse,
        )
        self.FunctionCallGetDataIn = grpclib.client.UnaryStreamMethod(
            channel,
            "/modal.client.ModalClient/FunctionCallGetDataIn",
            modal_proto.api_pb2.FunctionCallGetDataRequest,
            modal_proto.api_pb2.DataChunk,
        )
        self.FunctionCallPutDataOut = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/FunctionCallPutDataOut",
            modal_proto.api_pb2.FunctionCallPutDataRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.ImageGetOrCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/ImageGetOrCreate",
            modal_proto.api_pb2.ImageGetOrCreateRequest,
            modal_proto.api_pb2.ImageGetOrCreateResponse,
        )
        self.ImageJoinStreaming = grpclib.client.UnaryStreamMethod(
            channel,
            "/modal.client.ModalClient/ImageJoinStreaming",
            modal_proto.api_pb2.ImageJoinStreamingRequest,
            modal_proto.api_pb2.ImageJoinStreamingResponse,
        )
        self.MountPutFile = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/MountPutFile",
            modal_proto.api_pb2.MountPutFileRequest,
            modal_proto.api_pb2.MountPutFileResponse,
        )
        self.MountBuild = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/MountBuild",
            modal_proto.api_pb2.MountBuildRequest,
            modal_proto.api_pb2.MountBuildResponse,
        )
        self.QueueCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/QueueCreate",
            modal_proto.api_pb2.QueueCreateRequest,
            modal_proto.api_pb2.QueueCreateResponse,
        )
        self.QueueGet = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/QueueGet",
            modal_proto.api_pb2.QueueGetRequest,
            modal_proto.api_pb2.QueueGetResponse,
        )
        self.QueuePut = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/QueuePut",
            modal_proto.api_pb2.QueuePutRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.QueueLen = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/QueueLen",
            modal_proto.api_pb2.QueueLenRequest,
            modal_proto.api_pb2.QueueLenResponse,
        )
        self.SandboxCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SandboxCreate",
            modal_proto.api_pb2.SandboxCreateRequest,
            modal_proto.api_pb2.SandboxCreateResponse,
        )
        self.SandboxGetLogs = grpclib.client.UnaryStreamMethod(
            channel,
            "/modal.client.ModalClient/SandboxGetLogs",
            modal_proto.api_pb2.SandboxGetLogsRequest,
            modal_proto.api_pb2.TaskLogsBatch,
        )
        self.SandboxWait = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SandboxWait",
            modal_proto.api_pb2.SandboxWaitRequest,
            modal_proto.api_pb2.SandboxWaitResponse,
        )
        self.SandboxList = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SandboxList",
            modal_proto.api_pb2.SandboxListRequest,
            modal_proto.api_pb2.SandboxListResponse,
        )
        self.SandboxTerminate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SandboxTerminate",
            modal_proto.api_pb2.SandboxTerminateRequest,
            modal_proto.api_pb2.SandboxTerminateResponse,
        )
        self.SecretCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SecretCreate",
            modal_proto.api_pb2.SecretCreateRequest,
            modal_proto.api_pb2.SecretCreateResponse,
        )
        self.SecretList = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SecretList",
            modal_proto.api_pb2.SecretListRequest,
            modal_proto.api_pb2.SecretListResponse,
        )
        self.SharedVolumeCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SharedVolumeCreate",
            modal_proto.api_pb2.SharedVolumeCreateRequest,
            modal_proto.api_pb2.SharedVolumeCreateResponse,
        )
        self.SharedVolumeList = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SharedVolumeList",
            modal_proto.api_pb2.SharedVolumeListRequest,
            modal_proto.api_pb2.SharedVolumeListResponse,
        )
        self.SharedVolumeListFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SharedVolumeListFiles",
            modal_proto.api_pb2.SharedVolumeListFilesRequest,
            modal_proto.api_pb2.SharedVolumeListFilesResponse,
        )
        self.SharedVolumeListFilesStream = grpclib.client.UnaryStreamMethod(
            channel,
            "/modal.client.ModalClient/SharedVolumeListFilesStream",
            modal_proto.api_pb2.SharedVolumeListFilesRequest,
            modal_proto.api_pb2.SharedVolumeListFilesResponse,
        )
        self.SharedVolumePutFile = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SharedVolumePutFile",
            modal_proto.api_pb2.SharedVolumePutFileRequest,
            modal_proto.api_pb2.SharedVolumePutFileResponse,
        )
        self.SharedVolumeGetFile = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SharedVolumeGetFile",
            modal_proto.api_pb2.SharedVolumeGetFileRequest,
            modal_proto.api_pb2.SharedVolumeGetFileResponse,
        )
        self.SharedVolumeRemoveFile = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/SharedVolumeRemoveFile",
            modal_proto.api_pb2.SharedVolumeRemoveFileRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.TaskResult = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/TaskResult",
            modal_proto.api_pb2.TaskResultRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.TaskList = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/TaskList",
            modal_proto.api_pb2.TaskListRequest,
            modal_proto.api_pb2.TaskListResponse,
        )
        self.TokenFlowCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/TokenFlowCreate",
            modal_proto.api_pb2.TokenFlowCreateRequest,
            modal_proto.api_pb2.TokenFlowCreateResponse,
        )
        self.TokenFlowWait = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/TokenFlowWait",
            modal_proto.api_pb2.TokenFlowWaitRequest,
            modal_proto.api_pb2.TokenFlowWaitResponse,
        )
        self.TunnelStart = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/TunnelStart",
            modal_proto.api_pb2.TunnelStartRequest,
            modal_proto.api_pb2.TunnelStartResponse,
        )
        self.TunnelStop = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/TunnelStop",
            modal_proto.api_pb2.TunnelStopRequest,
            modal_proto.api_pb2.TunnelStopResponse,
        )
        self.VolumeCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/VolumeCreate",
            modal_proto.api_pb2.VolumeCreateRequest,
            modal_proto.api_pb2.VolumeCreateResponse,
        )
        self.VolumeCommit = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/VolumeCommit",
            modal_proto.api_pb2.VolumeCommitRequest,
            modal_proto.api_pb2.VolumeCommitResponse,
        )
        self.VolumeGetFile = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/VolumeGetFile",
            modal_proto.api_pb2.VolumeGetFileRequest,
            modal_proto.api_pb2.VolumeGetFileResponse,
        )
        self.VolumeList = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/VolumeList",
            modal_proto.api_pb2.VolumeListRequest,
            modal_proto.api_pb2.VolumeListResponse,
        )
        self.VolumeListFiles = grpclib.client.UnaryStreamMethod(
            channel,
            "/modal.client.ModalClient/VolumeListFiles",
            modal_proto.api_pb2.VolumeListFilesRequest,
            modal_proto.api_pb2.VolumeListFilesResponse,
        )
        self.VolumePutFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/VolumePutFiles",
            modal_proto.api_pb2.VolumePutFilesRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.VolumeReload = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/VolumeReload",
            modal_proto.api_pb2.VolumeReloadRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.VolumeRemoveFile = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/VolumeRemoveFile",
            modal_proto.api_pb2.VolumeRemoveFileRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.VolumeCopyFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            "/modal.client.ModalClient/VolumeCopyFiles",
            modal_proto.api_pb2.VolumeCopyFilesRequest,
            google.protobuf.empty_pb2.Empty,
        )
