// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.6
// source: modal_proto/task_command_router.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxStdioFileDescriptor int32

const (
	SandboxStdioFileDescriptor_SANDBOX_STDIO_FILE_DESCRIPTOR_STDOUT SandboxStdioFileDescriptor = 0
	SandboxStdioFileDescriptor_SANDBOX_STDIO_FILE_DESCRIPTOR_STDERR SandboxStdioFileDescriptor = 1
)

// Enum value maps for SandboxStdioFileDescriptor.
var (
	SandboxStdioFileDescriptor_name = map[int32]string{
		0: "SANDBOX_STDIO_FILE_DESCRIPTOR_STDOUT",
		1: "SANDBOX_STDIO_FILE_DESCRIPTOR_STDERR",
	}
	SandboxStdioFileDescriptor_value = map[string]int32{
		"SANDBOX_STDIO_FILE_DESCRIPTOR_STDOUT": 0,
		"SANDBOX_STDIO_FILE_DESCRIPTOR_STDERR": 1,
	}
)

func (x SandboxStdioFileDescriptor) Enum() *SandboxStdioFileDescriptor {
	p := new(SandboxStdioFileDescriptor)
	*p = x
	return p
}

func (x SandboxStdioFileDescriptor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxStdioFileDescriptor) Descriptor() protoreflect.EnumDescriptor {
	return file_modal_proto_task_command_router_proto_enumTypes[0].Descriptor()
}

func (SandboxStdioFileDescriptor) Type() protoreflect.EnumType {
	return &file_modal_proto_task_command_router_proto_enumTypes[0]
}

func (x SandboxStdioFileDescriptor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type TaskExecStderrConfig int32

const (
	// The output will be discarded.
	TaskExecStderrConfig_TASK_EXEC_STDERR_CONFIG_DEVNULL TaskExecStderrConfig = 0
	// The output will be streamed to the client.
	TaskExecStderrConfig_TASK_EXEC_STDERR_CONFIG_PIPE TaskExecStderrConfig = 1
	// A special value that can be used to indicate that the stderr stream should
	// be merged with the stdout stream.
	TaskExecStderrConfig_TASK_EXEC_STDERR_CONFIG_STDOUT TaskExecStderrConfig = 2
)

// Enum value maps for TaskExecStderrConfig.
var (
	TaskExecStderrConfig_name = map[int32]string{
		0: "TASK_EXEC_STDERR_CONFIG_DEVNULL",
		1: "TASK_EXEC_STDERR_CONFIG_PIPE",
		2: "TASK_EXEC_STDERR_CONFIG_STDOUT",
	}
	TaskExecStderrConfig_value = map[string]int32{
		"TASK_EXEC_STDERR_CONFIG_DEVNULL": 0,
		"TASK_EXEC_STDERR_CONFIG_PIPE":    1,
		"TASK_EXEC_STDERR_CONFIG_STDOUT":  2,
	}
)

func (x TaskExecStderrConfig) Enum() *TaskExecStderrConfig {
	p := new(TaskExecStderrConfig)
	*p = x
	return p
}

func (x TaskExecStderrConfig) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskExecStderrConfig) Descriptor() protoreflect.EnumDescriptor {
	return file_modal_proto_task_command_router_proto_enumTypes[1].Descriptor()
}

func (TaskExecStderrConfig) Type() protoreflect.EnumType {
	return &file_modal_proto_task_command_router_proto_enumTypes[1]
}

func (x TaskExecStderrConfig) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type TaskExecStdioFileDescriptor int32

const (
	// Read from stdout.
	TaskExecStdioFileDescriptor_TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDOUT TaskExecStdioFileDescriptor = 0
	// Read from stderr.
	TaskExecStdioFileDescriptor_TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDERR TaskExecStdioFileDescriptor = 1
)

// Enum value maps for TaskExecStdioFileDescriptor.
var (
	TaskExecStdioFileDescriptor_name = map[int32]string{
		0: "TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDOUT",
		1: "TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDERR",
	}
	TaskExecStdioFileDescriptor_value = map[string]int32{
		"TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDOUT": 0,
		"TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDERR": 1,
	}
)

func (x TaskExecStdioFileDescriptor) Enum() *TaskExecStdioFileDescriptor {
	p := new(TaskExecStdioFileDescriptor)
	*p = x
	return p
}

func (x TaskExecStdioFileDescriptor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskExecStdioFileDescriptor) Descriptor() protoreflect.EnumDescriptor {
	return file_modal_proto_task_command_router_proto_enumTypes[2].Descriptor()
}

func (TaskExecStdioFileDescriptor) Type() protoreflect.EnumType {
	return &file_modal_proto_task_command_router_proto_enumTypes[2]
}

func (x TaskExecStdioFileDescriptor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type TaskExecStdoutConfig int32

const (
	// The output will be discarded.
	TaskExecStdoutConfig_TASK_EXEC_STDOUT_CONFIG_DEVNULL TaskExecStdoutConfig = 0
	// The output will be streamed to the client.
	TaskExecStdoutConfig_TASK_EXEC_STDOUT_CONFIG_PIPE TaskExecStdoutConfig = 1
)

// Enum value maps for TaskExecStdoutConfig.
var (
	TaskExecStdoutConfig_name = map[int32]string{
		0: "TASK_EXEC_STDOUT_CONFIG_DEVNULL",
		1: "TASK_EXEC_STDOUT_CONFIG_PIPE",
	}
	TaskExecStdoutConfig_value = map[string]int32{
		"TASK_EXEC_STDOUT_CONFIG_DEVNULL": 0,
		"TASK_EXEC_STDOUT_CONFIG_PIPE":    1,
	}
)

func (x TaskExecStdoutConfig) Enum() *TaskExecStdoutConfig {
	p := new(TaskExecStdoutConfig)
	*p = x
	return p
}

func (x TaskExecStdoutConfig) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskExecStdoutConfig) Descriptor() protoreflect.EnumDescriptor {
	return file_modal_proto_task_command_router_proto_enumTypes[3].Descriptor()
}

func (TaskExecStdoutConfig) Type() protoreflect.EnumType {
	return &file_modal_proto_task_command_router_proto_enumTypes[3]
}

func (x TaskExecStdoutConfig) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SandboxStdinWriteV2Request struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_Offset uint64                 `protobuf:"varint,2,opt,name=offset,proto3"`
	xxx_hidden_Data   []byte                 `protobuf:"bytes,3,opt,name=data,proto3"`
	xxx_hidden_Eof    bool                   `protobuf:"varint,4,opt,name=eof,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SandboxStdinWriteV2Request) Reset() {
	*x = SandboxStdinWriteV2Request{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStdinWriteV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStdinWriteV2Request) ProtoMessage() {}

func (x *SandboxStdinWriteV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SandboxStdinWriteV2Request) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *SandboxStdinWriteV2Request) GetOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *SandboxStdinWriteV2Request) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *SandboxStdinWriteV2Request) GetEof() bool {
	if x != nil {
		return x.xxx_hidden_Eof
	}
	return false
}

func (x *SandboxStdinWriteV2Request) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *SandboxStdinWriteV2Request) SetOffset(v uint64) {
	x.xxx_hidden_Offset = v
}

func (x *SandboxStdinWriteV2Request) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

func (x *SandboxStdinWriteV2Request) SetEof(v bool) {
	x.xxx_hidden_Eof = v
}

type SandboxStdinWriteV2Request_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskId string
	Offset uint64
	Data   []byte
	Eof    bool
}

func (b0 SandboxStdinWriteV2Request_builder) Build() *SandboxStdinWriteV2Request {
	m0 := &SandboxStdinWriteV2Request{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_Eof = b.Eof
	return m0
}

type SandboxStdinWriteV2Response struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxStdinWriteV2Response) Reset() {
	*x = SandboxStdinWriteV2Response{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStdinWriteV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStdinWriteV2Response) ProtoMessage() {}

func (x *SandboxStdinWriteV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SandboxStdinWriteV2Response_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SandboxStdinWriteV2Response_builder) Build() *SandboxStdinWriteV2Response {
	m0 := &SandboxStdinWriteV2Response{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SandboxStdioReadV2Request struct {
	state                     protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_TaskId         string                     `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_Offset         uint64                     `protobuf:"varint,2,opt,name=offset,proto3"`
	xxx_hidden_FileDescriptor SandboxStdioFileDescriptor `protobuf:"varint,3,opt,name=file_descriptor,json=fileDescriptor,proto3,enum=modal.task_command_router.SandboxStdioFileDescriptor"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SandboxStdioReadV2Request) Reset() {
	*x = SandboxStdioReadV2Request{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStdioReadV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStdioReadV2Request) ProtoMessage() {}

func (x *SandboxStdioReadV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SandboxStdioReadV2Request) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *SandboxStdioReadV2Request) GetOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *SandboxStdioReadV2Request) GetFileDescriptor() SandboxStdioFileDescriptor {
	if x != nil {
		return x.xxx_hidden_FileDescriptor
	}
	return SandboxStdioFileDescriptor_SANDBOX_STDIO_FILE_DESCRIPTOR_STDOUT
}

func (x *SandboxStdioReadV2Request) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *SandboxStdioReadV2Request) SetOffset(v uint64) {
	x.xxx_hidden_Offset = v
}

func (x *SandboxStdioReadV2Request) SetFileDescriptor(v SandboxStdioFileDescriptor) {
	x.xxx_hidden_FileDescriptor = v
}

type SandboxStdioReadV2Request_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskId         string
	Offset         uint64
	FileDescriptor SandboxStdioFileDescriptor
}

func (b0 SandboxStdioReadV2Request_builder) Build() *SandboxStdioReadV2Request {
	m0 := &SandboxStdioReadV2Request{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_FileDescriptor = b.FileDescriptor
	return m0
}

type SandboxStdioReadV2Response struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data []byte                 `protobuf:"bytes,1,opt,name=data,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SandboxStdioReadV2Response) Reset() {
	*x = SandboxStdioReadV2Response{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStdioReadV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStdioReadV2Response) ProtoMessage() {}

func (x *SandboxStdioReadV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SandboxStdioReadV2Response) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *SandboxStdioReadV2Response) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

type SandboxStdioReadV2Response_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []byte
}

func (b0 SandboxStdioReadV2Response_builder) Build() *SandboxStdioReadV2Response {
	m0 := &SandboxStdioReadV2Response{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

type TaskContainerCreateRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3"`
	xxx_hidden_ImageId       string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3"`
	xxx_hidden_Args          []string               `protobuf:"bytes,5,rep,name=args,proto3"`
	xxx_hidden_Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Workdir       string                 `protobuf:"bytes,7,opt,name=workdir,proto3"`
	xxx_hidden_SecretIds     []string               `protobuf:"bytes,8,rep,name=secret_ids,json=secretIds,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TaskContainerCreateRequest) Reset() {
	*x = TaskContainerCreateRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContainerCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContainerCreateRequest) ProtoMessage() {}

func (x *TaskContainerCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskContainerCreateRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskContainerCreateRequest) GetContainerName() string {
	if x != nil {
		return x.xxx_hidden_ContainerName
	}
	return ""
}

func (x *TaskContainerCreateRequest) GetImageId() string {
	if x != nil {
		return x.xxx_hidden_ImageId
	}
	return ""
}

func (x *TaskContainerCreateRequest) GetArgs() []string {
	if x != nil {
		return x.xxx_hidden_Args
	}
	return nil
}

func (x *TaskContainerCreateRequest) GetEnv() map[string]string {
	if x != nil {
		return x.xxx_hidden_Env
	}
	return nil
}

func (x *TaskContainerCreateRequest) GetWorkdir() string {
	if x != nil {
		return x.xxx_hidden_Workdir
	}
	return ""
}

func (x *TaskContainerCreateRequest) GetSecretIds() []string {
	if x != nil {
		return x.xxx_hidden_SecretIds
	}
	return nil
}

func (x *TaskContainerCreateRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskContainerCreateRequest) SetContainerName(v string) {
	x.xxx_hidden_ContainerName = v
}

func (x *TaskContainerCreateRequest) SetImageId(v string) {
	x.xxx_hidden_ImageId = v
}

func (x *TaskContainerCreateRequest) SetArgs(v []string) {
	x.xxx_hidden_Args = v
}

func (x *TaskContainerCreateRequest) SetEnv(v map[string]string) {
	x.xxx_hidden_Env = v
}

func (x *TaskContainerCreateRequest) SetWorkdir(v string) {
	x.xxx_hidden_Workdir = v
}

func (x *TaskContainerCreateRequest) SetSecretIds(v []string) {
	x.xxx_hidden_SecretIds = v
}

type TaskContainerCreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskId string
	// Logical container name.
	ContainerName string
	ImageId       string
	Args          []string
	Env           map[string]string
	Workdir       string
	// Secret IDs to inject into the container as environment variables.
	SecretIds []string
}

func (b0 TaskContainerCreateRequest_builder) Build() *TaskContainerCreateRequest {
	m0 := &TaskContainerCreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_ContainerName = b.ContainerName
	x.xxx_hidden_ImageId = b.ImageId
	x.xxx_hidden_Args = b.Args
	x.xxx_hidden_Env = b.Env
	x.xxx_hidden_Workdir = b.Workdir
	x.xxx_hidden_SecretIds = b.SecretIds
	return m0
}

type TaskContainerCreateResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3"`
	xxx_hidden_ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TaskContainerCreateResponse) Reset() {
	*x = TaskContainerCreateResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContainerCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContainerCreateResponse) ProtoMessage() {}

func (x *TaskContainerCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskContainerCreateResponse) GetContainerId() string {
	if x != nil {
		return x.xxx_hidden_ContainerId
	}
	return ""
}

func (x *TaskContainerCreateResponse) GetContainerName() string {
	if x != nil {
		return x.xxx_hidden_ContainerName
	}
	return ""
}

func (x *TaskContainerCreateResponse) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = v
}

func (x *TaskContainerCreateResponse) SetContainerName(v string) {
	x.xxx_hidden_ContainerName = v
}

type TaskContainerCreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fully qualified container ID (for example, ctr-<ulid>).
	ContainerId string
	// Logical container name associated with this container.
	ContainerName string
}

func (b0 TaskContainerCreateResponse_builder) Build() *TaskContainerCreateResponse {
	m0 := &TaskContainerCreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ContainerId = b.ContainerId
	x.xxx_hidden_ContainerName = b.ContainerName
	return m0
}

type TaskContainerGetRequest struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_ContainerName     string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3"`
	xxx_hidden_IncludeTerminated bool                   `protobuf:"varint,3,opt,name=include_terminated,json=includeTerminated,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *TaskContainerGetRequest) Reset() {
	*x = TaskContainerGetRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContainerGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContainerGetRequest) ProtoMessage() {}

func (x *TaskContainerGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskContainerGetRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskContainerGetRequest) GetContainerName() string {
	if x != nil {
		return x.xxx_hidden_ContainerName
	}
	return ""
}

func (x *TaskContainerGetRequest) GetIncludeTerminated() bool {
	if x != nil {
		return x.xxx_hidden_IncludeTerminated
	}
	return false
}

func (x *TaskContainerGetRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskContainerGetRequest) SetContainerName(v string) {
	x.xxx_hidden_ContainerName = v
}

func (x *TaskContainerGetRequest) SetIncludeTerminated(v bool) {
	x.xxx_hidden_IncludeTerminated = v
}

type TaskContainerGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskId        string
	ContainerName string
	// Include the latest terminated container if the name is no longer active.
	IncludeTerminated bool
}

func (b0 TaskContainerGetRequest_builder) Build() *TaskContainerGetRequest {
	m0 := &TaskContainerGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_ContainerName = b.ContainerName
	x.xxx_hidden_IncludeTerminated = b.IncludeTerminated
	return m0
}

type TaskContainerGetResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Container *TaskContainerInfo     `protobuf:"bytes,1,opt,name=container,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TaskContainerGetResponse) Reset() {
	*x = TaskContainerGetResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContainerGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContainerGetResponse) ProtoMessage() {}

func (x *TaskContainerGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskContainerGetResponse) GetContainer() *TaskContainerInfo {
	if x != nil {
		return x.xxx_hidden_Container
	}
	return nil
}

func (x *TaskContainerGetResponse) SetContainer(v *TaskContainerInfo) {
	x.xxx_hidden_Container = v
}

func (x *TaskContainerGetResponse) HasContainer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Container != nil
}

func (x *TaskContainerGetResponse) ClearContainer() {
	x.xxx_hidden_Container = nil
}

type TaskContainerGetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Container *TaskContainerInfo
}

func (b0 TaskContainerGetResponse_builder) Build() *TaskContainerGetResponse {
	m0 := &TaskContainerGetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Container = b.Container
	return m0
}

type TaskContainerInfo struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3"`
	xxx_hidden_ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3"`
	xxx_hidden_Status        string                 `protobuf:"bytes,3,opt,name=status,proto3"`
	xxx_hidden_Result        *GenericResult         `protobuf:"bytes,4,opt,name=result,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TaskContainerInfo) Reset() {
	*x = TaskContainerInfo{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContainerInfo) ProtoMessage() {}

func (x *TaskContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskContainerInfo) GetContainerId() string {
	if x != nil {
		return x.xxx_hidden_ContainerId
	}
	return ""
}

func (x *TaskContainerInfo) GetContainerName() string {
	if x != nil {
		return x.xxx_hidden_ContainerName
	}
	return ""
}

func (x *TaskContainerInfo) GetStatus() string {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ""
}

func (x *TaskContainerInfo) GetResult() *GenericResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *TaskContainerInfo) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = v
}

func (x *TaskContainerInfo) SetContainerName(v string) {
	x.xxx_hidden_ContainerName = v
}

func (x *TaskContainerInfo) SetStatus(v string) {
	x.xxx_hidden_Status = v
}

func (x *TaskContainerInfo) SetResult(v *GenericResult) {
	x.xxx_hidden_Result = v
}

func (x *TaskContainerInfo) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *TaskContainerInfo) ClearResult() {
	x.xxx_hidden_Result = nil
}

type TaskContainerInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerId   string
	ContainerName string
	Status        string
	Result        *GenericResult
}

func (b0 TaskContainerInfo_builder) Build() *TaskContainerInfo {
	m0 := &TaskContainerInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ContainerId = b.ContainerId
	x.xxx_hidden_ContainerName = b.ContainerName
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_Result = b.Result
	return m0
}

type TaskContainerListRequest struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_IncludeTerminated bool                   `protobuf:"varint,2,opt,name=include_terminated,json=includeTerminated,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *TaskContainerListRequest) Reset() {
	*x = TaskContainerListRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContainerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContainerListRequest) ProtoMessage() {}

func (x *TaskContainerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskContainerListRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskContainerListRequest) GetIncludeTerminated() bool {
	if x != nil {
		return x.xxx_hidden_IncludeTerminated
	}
	return false
}

func (x *TaskContainerListRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskContainerListRequest) SetIncludeTerminated(v bool) {
	x.xxx_hidden_IncludeTerminated = v
}

type TaskContainerListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskId string
	// Include all tracked terminated containers in addition to active ones.
	IncludeTerminated bool
}

func (b0 TaskContainerListRequest_builder) Build() *TaskContainerListRequest {
	m0 := &TaskContainerListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_IncludeTerminated = b.IncludeTerminated
	return m0
}

type TaskContainerListResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Containers *[]*TaskContainerInfo  `protobuf:"bytes,1,rep,name=containers,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TaskContainerListResponse) Reset() {
	*x = TaskContainerListResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContainerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContainerListResponse) ProtoMessage() {}

func (x *TaskContainerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskContainerListResponse) GetContainers() []*TaskContainerInfo {
	if x != nil {
		if x.xxx_hidden_Containers != nil {
			return *x.xxx_hidden_Containers
		}
	}
	return nil
}

func (x *TaskContainerListResponse) SetContainers(v []*TaskContainerInfo) {
	x.xxx_hidden_Containers = &v
}

type TaskContainerListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Containers []*TaskContainerInfo
}

func (b0 TaskContainerListResponse_builder) Build() *TaskContainerListResponse {
	m0 := &TaskContainerListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Containers = &b.Containers
	return m0
}

type TaskContainerTerminateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId      string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_ContainerId string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TaskContainerTerminateRequest) Reset() {
	*x = TaskContainerTerminateRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContainerTerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContainerTerminateRequest) ProtoMessage() {}

func (x *TaskContainerTerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskContainerTerminateRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskContainerTerminateRequest) GetContainerId() string {
	if x != nil {
		return x.xxx_hidden_ContainerId
	}
	return ""
}

func (x *TaskContainerTerminateRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskContainerTerminateRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = v
}

type TaskContainerTerminateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskId      string
	ContainerId string
}

func (b0 TaskContainerTerminateRequest_builder) Build() *TaskContainerTerminateRequest {
	m0 := &TaskContainerTerminateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_ContainerId = b.ContainerId
	return m0
}

type TaskContainerTerminateResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskContainerTerminateResponse) Reset() {
	*x = TaskContainerTerminateResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContainerTerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContainerTerminateResponse) ProtoMessage() {}

func (x *TaskContainerTerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TaskContainerTerminateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TaskContainerTerminateResponse_builder) Build() *TaskContainerTerminateResponse {
	m0 := &TaskContainerTerminateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TaskContainerWaitRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId      string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_ContainerId string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3"`
	xxx_hidden_Timeout     float32                `protobuf:"fixed32,3,opt,name=timeout,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TaskContainerWaitRequest) Reset() {
	*x = TaskContainerWaitRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContainerWaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContainerWaitRequest) ProtoMessage() {}

func (x *TaskContainerWaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskContainerWaitRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskContainerWaitRequest) GetContainerId() string {
	if x != nil {
		return x.xxx_hidden_ContainerId
	}
	return ""
}

func (x *TaskContainerWaitRequest) GetTimeout() float32 {
	if x != nil {
		return x.xxx_hidden_Timeout
	}
	return 0
}

func (x *TaskContainerWaitRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskContainerWaitRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = v
}

func (x *TaskContainerWaitRequest) SetTimeout(v float32) {
	x.xxx_hidden_Timeout = v
}

type TaskContainerWaitRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskId      string
	ContainerId string
	Timeout     float32
}

func (b0 TaskContainerWaitRequest_builder) Build() *TaskContainerWaitRequest {
	m0 := &TaskContainerWaitRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_ContainerId = b.ContainerId
	x.xxx_hidden_Timeout = b.Timeout
	return m0
}

type TaskContainerWaitResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Result *GenericResult         `protobuf:"bytes,1,opt,name=result,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskContainerWaitResponse) Reset() {
	*x = TaskContainerWaitResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContainerWaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContainerWaitResponse) ProtoMessage() {}

func (x *TaskContainerWaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskContainerWaitResponse) GetResult() *GenericResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *TaskContainerWaitResponse) SetResult(v *GenericResult) {
	x.xxx_hidden_Result = v
}

func (x *TaskContainerWaitResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *TaskContainerWaitResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

type TaskContainerWaitResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Result *GenericResult
}

func (b0 TaskContainerWaitResponse_builder) Build() *TaskContainerWaitResponse {
	m0 := &TaskContainerWaitResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Result = b.Result
	return m0
}

type TaskExecPollRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_ExecId string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskExecPollRequest) Reset() {
	*x = TaskExecPollRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecPollRequest) ProtoMessage() {}

func (x *TaskExecPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskExecPollRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskExecPollRequest) GetExecId() string {
	if x != nil {
		return x.xxx_hidden_ExecId
	}
	return ""
}

func (x *TaskExecPollRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskExecPollRequest) SetExecId(v string) {
	x.xxx_hidden_ExecId = v
}

type TaskExecPollRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the task running the exec'd command.
	TaskId string
	// The execution ID of the command to wait on.
	ExecId string
}

func (b0 TaskExecPollRequest_builder) Build() *TaskExecPollRequest {
	m0 := &TaskExecPollRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_ExecId = b.ExecId
	return m0
}

// The response to a TaskExecPollRequest. If the exec'd command has not
// completed, exit_status will be unset.
type TaskExecPollResponse struct {
	state                 protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_ExitStatus isTaskExecPollResponse_ExitStatus `protobuf_oneof:"exit_status"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TaskExecPollResponse) Reset() {
	*x = TaskExecPollResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecPollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecPollResponse) ProtoMessage() {}

func (x *TaskExecPollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskExecPollResponse) GetCode() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_ExitStatus.(*taskExecPollResponse_Code); ok {
			return x.Code
		}
	}
	return 0
}

func (x *TaskExecPollResponse) GetSignal() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_ExitStatus.(*taskExecPollResponse_Signal); ok {
			return x.Signal
		}
	}
	return 0
}

func (x *TaskExecPollResponse) SetCode(v int32) {
	x.xxx_hidden_ExitStatus = &taskExecPollResponse_Code{v}
}

func (x *TaskExecPollResponse) SetSignal(v int32) {
	x.xxx_hidden_ExitStatus = &taskExecPollResponse_Signal{v}
}

func (x *TaskExecPollResponse) HasExitStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExitStatus != nil
}

func (x *TaskExecPollResponse) HasCode() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_ExitStatus.(*taskExecPollResponse_Code)
	return ok
}

func (x *TaskExecPollResponse) HasSignal() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_ExitStatus.(*taskExecPollResponse_Signal)
	return ok
}

func (x *TaskExecPollResponse) ClearExitStatus() {
	x.xxx_hidden_ExitStatus = nil
}

func (x *TaskExecPollResponse) ClearCode() {
	if _, ok := x.xxx_hidden_ExitStatus.(*taskExecPollResponse_Code); ok {
		x.xxx_hidden_ExitStatus = nil
	}
}

func (x *TaskExecPollResponse) ClearSignal() {
	if _, ok := x.xxx_hidden_ExitStatus.(*taskExecPollResponse_Signal); ok {
		x.xxx_hidden_ExitStatus = nil
	}
}

const TaskExecPollResponse_ExitStatus_not_set_case case_TaskExecPollResponse_ExitStatus = 0
const TaskExecPollResponse_Code_case case_TaskExecPollResponse_ExitStatus = 1
const TaskExecPollResponse_Signal_case case_TaskExecPollResponse_ExitStatus = 2

func (x *TaskExecPollResponse) WhichExitStatus() case_TaskExecPollResponse_ExitStatus {
	if x == nil {
		return TaskExecPollResponse_ExitStatus_not_set_case
	}
	switch x.xxx_hidden_ExitStatus.(type) {
	case *taskExecPollResponse_Code:
		return TaskExecPollResponse_Code_case
	case *taskExecPollResponse_Signal:
		return TaskExecPollResponse_Signal_case
	default:
		return TaskExecPollResponse_ExitStatus_not_set_case
	}
}

type TaskExecPollResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_ExitStatus:
	// The exit code of the command.
	Code *int32
	// The signal that terminated the command.
	Signal *int32
	// -- end of xxx_hidden_ExitStatus
}

func (b0 TaskExecPollResponse_builder) Build() *TaskExecPollResponse {
	m0 := &TaskExecPollResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Code != nil {
		x.xxx_hidden_ExitStatus = &taskExecPollResponse_Code{*b.Code}
	}
	if b.Signal != nil {
		x.xxx_hidden_ExitStatus = &taskExecPollResponse_Signal{*b.Signal}
	}
	return m0
}

type case_TaskExecPollResponse_ExitStatus protoreflect.FieldNumber

func (x case_TaskExecPollResponse_ExitStatus) String() string {
	md := file_modal_proto_task_command_router_proto_msgTypes[16].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isTaskExecPollResponse_ExitStatus interface {
	isTaskExecPollResponse_ExitStatus()
}

type taskExecPollResponse_Code struct {
	// The exit code of the command.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3,oneof"`
}

type taskExecPollResponse_Signal struct {
	// The signal that terminated the command.
	Signal int32 `protobuf:"varint,2,opt,name=signal,proto3,oneof"`
}

func (*taskExecPollResponse_Code) isTaskExecPollResponse_ExitStatus() {}

func (*taskExecPollResponse_Signal) isTaskExecPollResponse_ExitStatus() {}

type TaskExecStartRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId       string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_ExecId       string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3"`
	xxx_hidden_CommandArgs  []string               `protobuf:"bytes,3,rep,name=command_args,json=commandArgs,proto3"`
	xxx_hidden_StdoutConfig TaskExecStdoutConfig   `protobuf:"varint,4,opt,name=stdout_config,json=stdoutConfig,proto3,enum=modal.task_command_router.TaskExecStdoutConfig"`
	xxx_hidden_StderrConfig TaskExecStderrConfig   `protobuf:"varint,5,opt,name=stderr_config,json=stderrConfig,proto3,enum=modal.task_command_router.TaskExecStderrConfig"`
	xxx_hidden_TimeoutSecs  uint32                 `protobuf:"varint,6,opt,name=timeout_secs,json=timeoutSecs,proto3,oneof"`
	xxx_hidden_Workdir      *string                `protobuf:"bytes,7,opt,name=workdir,proto3,oneof"`
	xxx_hidden_SecretIds    []string               `protobuf:"bytes,8,rep,name=secret_ids,json=secretIds,proto3"`
	xxx_hidden_PtyInfo      *PTYInfo               `protobuf:"bytes,9,opt,name=pty_info,json=ptyInfo,proto3,oneof"`
	xxx_hidden_RuntimeDebug bool                   `protobuf:"varint,10,opt,name=runtime_debug,json=runtimeDebug,proto3"`
	xxx_hidden_ContainerId  string                 `protobuf:"bytes,11,opt,name=container_id,json=containerId,proto3"`
	xxx_hidden_Env          map[string]string      `protobuf:"bytes,12,rep,name=env,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TaskExecStartRequest) Reset() {
	*x = TaskExecStartRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecStartRequest) ProtoMessage() {}

func (x *TaskExecStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskExecStartRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskExecStartRequest) GetExecId() string {
	if x != nil {
		return x.xxx_hidden_ExecId
	}
	return ""
}

func (x *TaskExecStartRequest) GetCommandArgs() []string {
	if x != nil {
		return x.xxx_hidden_CommandArgs
	}
	return nil
}

func (x *TaskExecStartRequest) GetStdoutConfig() TaskExecStdoutConfig {
	if x != nil {
		return x.xxx_hidden_StdoutConfig
	}
	return TaskExecStdoutConfig_TASK_EXEC_STDOUT_CONFIG_DEVNULL
}

func (x *TaskExecStartRequest) GetStderrConfig() TaskExecStderrConfig {
	if x != nil {
		return x.xxx_hidden_StderrConfig
	}
	return TaskExecStderrConfig_TASK_EXEC_STDERR_CONFIG_DEVNULL
}

func (x *TaskExecStartRequest) GetTimeoutSecs() uint32 {
	if x != nil {
		return x.xxx_hidden_TimeoutSecs
	}
	return 0
}

func (x *TaskExecStartRequest) GetWorkdir() string {
	if x != nil {
		if x.xxx_hidden_Workdir != nil {
			return *x.xxx_hidden_Workdir
		}
		return ""
	}
	return ""
}

func (x *TaskExecStartRequest) GetSecretIds() []string {
	if x != nil {
		return x.xxx_hidden_SecretIds
	}
	return nil
}

func (x *TaskExecStartRequest) GetPtyInfo() *PTYInfo {
	if x != nil {
		return x.xxx_hidden_PtyInfo
	}
	return nil
}

func (x *TaskExecStartRequest) GetRuntimeDebug() bool {
	if x != nil {
		return x.xxx_hidden_RuntimeDebug
	}
	return false
}

func (x *TaskExecStartRequest) GetContainerId() string {
	if x != nil {
		return x.xxx_hidden_ContainerId
	}
	return ""
}

func (x *TaskExecStartRequest) GetEnv() map[string]string {
	if x != nil {
		return x.xxx_hidden_Env
	}
	return nil
}

func (x *TaskExecStartRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskExecStartRequest) SetExecId(v string) {
	x.xxx_hidden_ExecId = v
}

func (x *TaskExecStartRequest) SetCommandArgs(v []string) {
	x.xxx_hidden_CommandArgs = v
}

func (x *TaskExecStartRequest) SetStdoutConfig(v TaskExecStdoutConfig) {
	x.xxx_hidden_StdoutConfig = v
}

func (x *TaskExecStartRequest) SetStderrConfig(v TaskExecStderrConfig) {
	x.xxx_hidden_StderrConfig = v
}

func (x *TaskExecStartRequest) SetTimeoutSecs(v uint32) {
	x.xxx_hidden_TimeoutSecs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *TaskExecStartRequest) SetWorkdir(v string) {
	x.xxx_hidden_Workdir = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 12)
}

func (x *TaskExecStartRequest) SetSecretIds(v []string) {
	x.xxx_hidden_SecretIds = v
}

func (x *TaskExecStartRequest) SetPtyInfo(v *PTYInfo) {
	x.xxx_hidden_PtyInfo = v
}

func (x *TaskExecStartRequest) SetRuntimeDebug(v bool) {
	x.xxx_hidden_RuntimeDebug = v
}

func (x *TaskExecStartRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = v
}

func (x *TaskExecStartRequest) SetEnv(v map[string]string) {
	x.xxx_hidden_Env = v
}

func (x *TaskExecStartRequest) HasTimeoutSecs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *TaskExecStartRequest) HasWorkdir() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *TaskExecStartRequest) HasPtyInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PtyInfo != nil
}

func (x *TaskExecStartRequest) ClearTimeoutSecs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_TimeoutSecs = 0
}

func (x *TaskExecStartRequest) ClearWorkdir() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Workdir = nil
}

func (x *TaskExecStartRequest) ClearPtyInfo() {
	x.xxx_hidden_PtyInfo = nil
}

type TaskExecStartRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the task to execute the command in.
	TaskId string
	// Execution ID. This ID will be used to identify the execution for other
	// requests and ensure exec commands are idempotent.
	ExecId string
	// Command arguments to execute.
	CommandArgs []string
	// Configures how the stdout of the command will be handled.
	StdoutConfig TaskExecStdoutConfig
	// Configures how the stderr of the command will be handled.
	StderrConfig TaskExecStderrConfig
	// Timeout in seconds for the exec'd command to exit. If the command does not
	// exit within this duration, the command will be killed. This is NOT the
	// timeout for the ExecStartRequest RPC to complete.
	TimeoutSecs *uint32
	// Working directory for the command.
	Workdir *string
	// Secret IDs to mount into the task.
	SecretIds []string
	// PTY info for the command.
	PtyInfo *PTYInfo
	// Enable debugging capabilities on the container runtime. Used only for
	// internal debugging.
	RuntimeDebug bool
	// Fully qualified target container ID. Empty targets the main container.
	ContainerId string
	// Environment variables to set directly for the exec'd command.
	Env map[string]string
}

func (b0 TaskExecStartRequest_builder) Build() *TaskExecStartRequest {
	m0 := &TaskExecStartRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_ExecId = b.ExecId
	x.xxx_hidden_CommandArgs = b.CommandArgs
	x.xxx_hidden_StdoutConfig = b.StdoutConfig
	x.xxx_hidden_StderrConfig = b.StderrConfig
	if b.TimeoutSecs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_TimeoutSecs = *b.TimeoutSecs
	}
	if b.Workdir != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 12)
		x.xxx_hidden_Workdir = b.Workdir
	}
	x.xxx_hidden_SecretIds = b.SecretIds
	x.xxx_hidden_PtyInfo = b.PtyInfo
	x.xxx_hidden_RuntimeDebug = b.RuntimeDebug
	x.xxx_hidden_ContainerId = b.ContainerId
	x.xxx_hidden_Env = b.Env
	return m0
}

type TaskExecStartResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecStartResponse) Reset() {
	*x = TaskExecStartResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecStartResponse) ProtoMessage() {}

func (x *TaskExecStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TaskExecStartResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TaskExecStartResponse_builder) Build() *TaskExecStartResponse {
	m0 := &TaskExecStartResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TaskExecStdinWriteRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_ExecId string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3"`
	xxx_hidden_Offset uint64                 `protobuf:"varint,3,opt,name=offset,proto3"`
	xxx_hidden_Data   []byte                 `protobuf:"bytes,4,opt,name=data,proto3"`
	xxx_hidden_Eof    bool                   `protobuf:"varint,5,opt,name=eof,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskExecStdinWriteRequest) Reset() {
	*x = TaskExecStdinWriteRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecStdinWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecStdinWriteRequest) ProtoMessage() {}

func (x *TaskExecStdinWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskExecStdinWriteRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskExecStdinWriteRequest) GetExecId() string {
	if x != nil {
		return x.xxx_hidden_ExecId
	}
	return ""
}

func (x *TaskExecStdinWriteRequest) GetOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *TaskExecStdinWriteRequest) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *TaskExecStdinWriteRequest) GetEof() bool {
	if x != nil {
		return x.xxx_hidden_Eof
	}
	return false
}

func (x *TaskExecStdinWriteRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskExecStdinWriteRequest) SetExecId(v string) {
	x.xxx_hidden_ExecId = v
}

func (x *TaskExecStdinWriteRequest) SetOffset(v uint64) {
	x.xxx_hidden_Offset = v
}

func (x *TaskExecStdinWriteRequest) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

func (x *TaskExecStdinWriteRequest) SetEof(v bool) {
	x.xxx_hidden_Eof = v
}

type TaskExecStdinWriteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the task running the exec'd command.
	TaskId string
	// The execution ID of the command to write to.
	ExecId string
	// The offset to start writing to. This is used to resume writing from the
	// last write position if the connection is closed and reopened.
	Offset uint64
	Data   []byte
	// If true, close the stdin stream after writing any provided data.
	// This signals EOF to the exec'd process.
	Eof bool
}

func (b0 TaskExecStdinWriteRequest_builder) Build() *TaskExecStdinWriteRequest {
	m0 := &TaskExecStdinWriteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_ExecId = b.ExecId
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_Eof = b.Eof
	return m0
}

type TaskExecStdinWriteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecStdinWriteResponse) Reset() {
	*x = TaskExecStdinWriteResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecStdinWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecStdinWriteResponse) ProtoMessage() {}

func (x *TaskExecStdinWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TaskExecStdinWriteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TaskExecStdinWriteResponse_builder) Build() *TaskExecStdinWriteResponse {
	m0 := &TaskExecStdinWriteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TaskExecStdioReadRequest struct {
	state                     protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_TaskId         string                      `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_ExecId         string                      `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3"`
	xxx_hidden_Offset         uint64                      `protobuf:"varint,3,opt,name=offset,proto3"`
	xxx_hidden_FileDescriptor TaskExecStdioFileDescriptor `protobuf:"varint,4,opt,name=file_descriptor,json=fileDescriptor,proto3,enum=modal.task_command_router.TaskExecStdioFileDescriptor"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TaskExecStdioReadRequest) Reset() {
	*x = TaskExecStdioReadRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecStdioReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecStdioReadRequest) ProtoMessage() {}

func (x *TaskExecStdioReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskExecStdioReadRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskExecStdioReadRequest) GetExecId() string {
	if x != nil {
		return x.xxx_hidden_ExecId
	}
	return ""
}

func (x *TaskExecStdioReadRequest) GetOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *TaskExecStdioReadRequest) GetFileDescriptor() TaskExecStdioFileDescriptor {
	if x != nil {
		return x.xxx_hidden_FileDescriptor
	}
	return TaskExecStdioFileDescriptor_TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDOUT
}

func (x *TaskExecStdioReadRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskExecStdioReadRequest) SetExecId(v string) {
	x.xxx_hidden_ExecId = v
}

func (x *TaskExecStdioReadRequest) SetOffset(v uint64) {
	x.xxx_hidden_Offset = v
}

func (x *TaskExecStdioReadRequest) SetFileDescriptor(v TaskExecStdioFileDescriptor) {
	x.xxx_hidden_FileDescriptor = v
}

type TaskExecStdioReadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the task running the exec'd command.
	TaskId string
	// The execution ID of the command to read from.
	ExecId string
	// The offset to start reading from. This is used to resume reading from the
	// last read position if the connection is closed and reopened.
	Offset uint64
	// Which file descriptor to read from.
	FileDescriptor TaskExecStdioFileDescriptor
}

func (b0 TaskExecStdioReadRequest_builder) Build() *TaskExecStdioReadRequest {
	m0 := &TaskExecStdioReadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_ExecId = b.ExecId
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_FileDescriptor = b.FileDescriptor
	return m0
}

type TaskExecStdioReadResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data []byte                 `protobuf:"bytes,1,opt,name=data,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskExecStdioReadResponse) Reset() {
	*x = TaskExecStdioReadResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecStdioReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecStdioReadResponse) ProtoMessage() {}

func (x *TaskExecStdioReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskExecStdioReadResponse) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *TaskExecStdioReadResponse) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

type TaskExecStdioReadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The data read from the file descriptor.
	Data []byte
}

func (b0 TaskExecStdioReadResponse_builder) Build() *TaskExecStdioReadResponse {
	m0 := &TaskExecStdioReadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

type TaskExecWaitRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_ExecId string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskExecWaitRequest) Reset() {
	*x = TaskExecWaitRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecWaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecWaitRequest) ProtoMessage() {}

func (x *TaskExecWaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskExecWaitRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskExecWaitRequest) GetExecId() string {
	if x != nil {
		return x.xxx_hidden_ExecId
	}
	return ""
}

func (x *TaskExecWaitRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskExecWaitRequest) SetExecId(v string) {
	x.xxx_hidden_ExecId = v
}

type TaskExecWaitRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the task running the exec'd command.
	TaskId string
	// The execution ID of the command to wait on.
	ExecId string
}

func (b0 TaskExecWaitRequest_builder) Build() *TaskExecWaitRequest {
	m0 := &TaskExecWaitRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_ExecId = b.ExecId
	return m0
}

type TaskExecWaitResponse struct {
	state                 protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_ExitStatus isTaskExecWaitResponse_ExitStatus `protobuf_oneof:"exit_status"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TaskExecWaitResponse) Reset() {
	*x = TaskExecWaitResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecWaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecWaitResponse) ProtoMessage() {}

func (x *TaskExecWaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskExecWaitResponse) GetCode() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_ExitStatus.(*taskExecWaitResponse_Code); ok {
			return x.Code
		}
	}
	return 0
}

func (x *TaskExecWaitResponse) GetSignal() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_ExitStatus.(*taskExecWaitResponse_Signal); ok {
			return x.Signal
		}
	}
	return 0
}

func (x *TaskExecWaitResponse) SetCode(v int32) {
	x.xxx_hidden_ExitStatus = &taskExecWaitResponse_Code{v}
}

func (x *TaskExecWaitResponse) SetSignal(v int32) {
	x.xxx_hidden_ExitStatus = &taskExecWaitResponse_Signal{v}
}

func (x *TaskExecWaitResponse) HasExitStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExitStatus != nil
}

func (x *TaskExecWaitResponse) HasCode() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_ExitStatus.(*taskExecWaitResponse_Code)
	return ok
}

func (x *TaskExecWaitResponse) HasSignal() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_ExitStatus.(*taskExecWaitResponse_Signal)
	return ok
}

func (x *TaskExecWaitResponse) ClearExitStatus() {
	x.xxx_hidden_ExitStatus = nil
}

func (x *TaskExecWaitResponse) ClearCode() {
	if _, ok := x.xxx_hidden_ExitStatus.(*taskExecWaitResponse_Code); ok {
		x.xxx_hidden_ExitStatus = nil
	}
}

func (x *TaskExecWaitResponse) ClearSignal() {
	if _, ok := x.xxx_hidden_ExitStatus.(*taskExecWaitResponse_Signal); ok {
		x.xxx_hidden_ExitStatus = nil
	}
}

const TaskExecWaitResponse_ExitStatus_not_set_case case_TaskExecWaitResponse_ExitStatus = 0
const TaskExecWaitResponse_Code_case case_TaskExecWaitResponse_ExitStatus = 1
const TaskExecWaitResponse_Signal_case case_TaskExecWaitResponse_ExitStatus = 2

func (x *TaskExecWaitResponse) WhichExitStatus() case_TaskExecWaitResponse_ExitStatus {
	if x == nil {
		return TaskExecWaitResponse_ExitStatus_not_set_case
	}
	switch x.xxx_hidden_ExitStatus.(type) {
	case *taskExecWaitResponse_Code:
		return TaskExecWaitResponse_Code_case
	case *taskExecWaitResponse_Signal:
		return TaskExecWaitResponse_Signal_case
	default:
		return TaskExecWaitResponse_ExitStatus_not_set_case
	}
}

type TaskExecWaitResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_ExitStatus:
	// The exit code of the command.
	Code *int32
	// The signal that terminated the command.
	Signal *int32
	// -- end of xxx_hidden_ExitStatus
}

func (b0 TaskExecWaitResponse_builder) Build() *TaskExecWaitResponse {
	m0 := &TaskExecWaitResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Code != nil {
		x.xxx_hidden_ExitStatus = &taskExecWaitResponse_Code{*b.Code}
	}
	if b.Signal != nil {
		x.xxx_hidden_ExitStatus = &taskExecWaitResponse_Signal{*b.Signal}
	}
	return m0
}

type case_TaskExecWaitResponse_ExitStatus protoreflect.FieldNumber

func (x case_TaskExecWaitResponse_ExitStatus) String() string {
	md := file_modal_proto_task_command_router_proto_msgTypes[24].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isTaskExecWaitResponse_ExitStatus interface {
	isTaskExecWaitResponse_ExitStatus()
}

type taskExecWaitResponse_Code struct {
	// The exit code of the command.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3,oneof"`
}

type taskExecWaitResponse_Signal struct {
	// The signal that terminated the command.
	Signal int32 `protobuf:"varint,2,opt,name=signal,proto3,oneof"`
}

func (*taskExecWaitResponse_Code) isTaskExecWaitResponse_ExitStatus() {}

func (*taskExecWaitResponse_Signal) isTaskExecWaitResponse_ExitStatus() {}

type TaskMountDirectoryRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId  string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_Path    []byte                 `protobuf:"bytes,2,opt,name=path,proto3"`
	xxx_hidden_ImageId string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskMountDirectoryRequest) Reset() {
	*x = TaskMountDirectoryRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMountDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMountDirectoryRequest) ProtoMessage() {}

func (x *TaskMountDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskMountDirectoryRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskMountDirectoryRequest) GetPath() []byte {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return nil
}

func (x *TaskMountDirectoryRequest) GetImageId() string {
	if x != nil {
		return x.xxx_hidden_ImageId
	}
	return ""
}

func (x *TaskMountDirectoryRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskMountDirectoryRequest) SetPath(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Path = v
}

func (x *TaskMountDirectoryRequest) SetImageId(v string) {
	x.xxx_hidden_ImageId = v
}

type TaskMountDirectoryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskId  string
	Path    []byte
	ImageId string
}

func (b0 TaskMountDirectoryRequest_builder) Build() *TaskMountDirectoryRequest {
	m0 := &TaskMountDirectoryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_ImageId = b.ImageId
	return m0
}

type TaskSnapshotDirectoryRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId     string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_Path       []byte                 `protobuf:"bytes,2,opt,name=path,proto3"`
	xxx_hidden_SnapshotId string                 `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TaskSnapshotDirectoryRequest) Reset() {
	*x = TaskSnapshotDirectoryRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSnapshotDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSnapshotDirectoryRequest) ProtoMessage() {}

func (x *TaskSnapshotDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskSnapshotDirectoryRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskSnapshotDirectoryRequest) GetPath() []byte {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return nil
}

func (x *TaskSnapshotDirectoryRequest) GetSnapshotId() string {
	if x != nil {
		return x.xxx_hidden_SnapshotId
	}
	return ""
}

func (x *TaskSnapshotDirectoryRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskSnapshotDirectoryRequest) SetPath(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Path = v
}

func (x *TaskSnapshotDirectoryRequest) SetSnapshotId(v string) {
	x.xxx_hidden_SnapshotId = v
}

type TaskSnapshotDirectoryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskId string
	Path   []byte
	// A unique ID to ensure idempotency of directory snapshot requests.
	SnapshotId string
}

func (b0 TaskSnapshotDirectoryRequest_builder) Build() *TaskSnapshotDirectoryRequest {
	m0 := &TaskSnapshotDirectoryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_SnapshotId = b.SnapshotId
	return m0
}

type TaskSnapshotDirectoryResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ImageId string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskSnapshotDirectoryResponse) Reset() {
	*x = TaskSnapshotDirectoryResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSnapshotDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSnapshotDirectoryResponse) ProtoMessage() {}

func (x *TaskSnapshotDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskSnapshotDirectoryResponse) GetImageId() string {
	if x != nil {
		return x.xxx_hidden_ImageId
	}
	return ""
}

func (x *TaskSnapshotDirectoryResponse) SetImageId(v string) {
	x.xxx_hidden_ImageId = v
}

type TaskSnapshotDirectoryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ImageId string
}

func (b0 TaskSnapshotDirectoryResponse_builder) Build() *TaskSnapshotDirectoryResponse {
	m0 := &TaskSnapshotDirectoryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ImageId = b.ImageId
	return m0
}

type TaskUnmountDirectoryRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3"`
	xxx_hidden_Path   []byte                 `protobuf:"bytes,2,opt,name=path,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskUnmountDirectoryRequest) Reset() {
	*x = TaskUnmountDirectoryRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUnmountDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUnmountDirectoryRequest) ProtoMessage() {}

func (x *TaskUnmountDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TaskUnmountDirectoryRequest) GetTaskId() string {
	if x != nil {
		return x.xxx_hidden_TaskId
	}
	return ""
}

func (x *TaskUnmountDirectoryRequest) GetPath() []byte {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return nil
}

func (x *TaskUnmountDirectoryRequest) SetTaskId(v string) {
	x.xxx_hidden_TaskId = v
}

func (x *TaskUnmountDirectoryRequest) SetPath(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Path = v
}

type TaskUnmountDirectoryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskId string
	Path   []byte
}

func (b0 TaskUnmountDirectoryRequest_builder) Build() *TaskUnmountDirectoryRequest {
	m0 := &TaskUnmountDirectoryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskId = b.TaskId
	x.xxx_hidden_Path = b.Path
	return m0
}

var File_modal_proto_task_command_router_proto protoreflect.FileDescriptor

const file_modal_proto_task_command_router_proto_rawDesc = "" +
	"\n" +
	"%modal_proto/task_command_router.proto\x12\x19modal.task_command_router\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15modal_proto/api.proto\"s\n" +
	"\x1aSandboxStdinWriteV2Request\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"\x1d\n" +
	"\x1bSandboxStdinWriteV2Response\"\xac\x01\n" +
	"\x19SandboxStdioReadV2Request\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12^\n" +
	"\x0ffile_descriptor\x18\x03 \x01(\x0e25.modal.task_command_router.SandboxStdioFileDescriptorR\x0efileDescriptor\"0\n" +
	"\x1aSandboxStdioReadV2Response\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xce\x02\n" +
	"\x1aTaskContainerCreateRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12P\n" +
	"\x03env\x18\x06 \x03(\v2>.modal.task_command_router.TaskContainerCreateRequest.EnvEntryR\x03env\x12\x18\n" +
	"\aworkdir\x18\a \x01(\tR\aworkdir\x12\x1d\n" +
	"\n" +
	"secret_ids\x18\b \x03(\tR\tsecretIds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x1bTaskContainerCreateResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\"\x88\x01\n" +
	"\x17TaskContainerGetRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12-\n" +
	"\x12include_terminated\x18\x03 \x01(\bR\x11includeTerminated\"f\n" +
	"\x18TaskContainerGetResponse\x12J\n" +
	"\tcontainer\x18\x01 \x01(\v2,.modal.task_command_router.TaskContainerInfoR\tcontainer\"\xaa\x01\n" +
	"\x11TaskContainerInfo\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x123\n" +
	"\x06result\x18\x04 \x01(\v2\x1b.modal.client.GenericResultR\x06result\"b\n" +
	"\x18TaskContainerListRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\x12include_terminated\x18\x02 \x01(\bR\x11includeTerminated\"i\n" +
	"\x19TaskContainerListResponse\x12L\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2,.modal.task_command_router.TaskContainerInfoR\n" +
	"containers\"[\n" +
	"\x1dTaskContainerTerminateRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\" \n" +
	"\x1eTaskContainerTerminateResponse\"p\n" +
	"\x18TaskContainerWaitRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x02R\atimeout\"P\n" +
	"\x19TaskContainerWaitResponse\x123\n" +
	"\x06result\x18\x01 \x01(\v2\x1b.modal.client.GenericResultR\x06result\"G\n" +
	"\x13TaskExecPollRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\"U\n" +
	"\x14TaskExecPollResponse\x12\x14\n" +
	"\x04code\x18\x01 \x01(\x05H\x00R\x04code\x12\x18\n" +
	"\x06signal\x18\x02 \x01(\x05H\x00R\x06signalB\r\n" +
	"\vexit_status\"\xaa\x05\n" +
	"\x14TaskExecStartRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12!\n" +
	"\fcommand_args\x18\x03 \x03(\tR\vcommandArgs\x12T\n" +
	"\rstdout_config\x18\x04 \x01(\x0e2/.modal.task_command_router.TaskExecStdoutConfigR\fstdoutConfig\x12T\n" +
	"\rstderr_config\x18\x05 \x01(\x0e2/.modal.task_command_router.TaskExecStderrConfigR\fstderrConfig\x12&\n" +
	"\ftimeout_secs\x18\x06 \x01(\rH\x00R\vtimeoutSecs\x88\x01\x01\x12\x1d\n" +
	"\aworkdir\x18\a \x01(\tH\x01R\aworkdir\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"secret_ids\x18\b \x03(\tR\tsecretIds\x125\n" +
	"\bpty_info\x18\t \x01(\v2\x15.modal.client.PTYInfoH\x02R\aptyInfo\x88\x01\x01\x12#\n" +
	"\rruntime_debug\x18\n" +
	" \x01(\bR\fruntimeDebug\x12!\n" +
	"\fcontainer_id\x18\v \x01(\tR\vcontainerId\x12J\n" +
	"\x03env\x18\f \x03(\v28.modal.task_command_router.TaskExecStartRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_timeout_secsB\n" +
	"\n" +
	"\b_workdirB\v\n" +
	"\t_pty_info\"\x17\n" +
	"\x15TaskExecStartResponse\"\x8b\x01\n" +
	"\x19TaskExecStdinWriteRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x05 \x01(\bR\x03eof\"\x1c\n" +
	"\x1aTaskExecStdinWriteResponse\"\xc5\x01\n" +
	"\x18TaskExecStdioReadRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12_\n" +
	"\x0ffile_descriptor\x18\x04 \x01(\x0e26.modal.task_command_router.TaskExecStdioFileDescriptorR\x0efileDescriptor\"/\n" +
	"\x19TaskExecStdioReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"G\n" +
	"\x13TaskExecWaitRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\"U\n" +
	"\x14TaskExecWaitResponse\x12\x14\n" +
	"\x04code\x18\x01 \x01(\x05H\x00R\x04code\x12\x18\n" +
	"\x06signal\x18\x02 \x01(\x05H\x00R\x06signalB\r\n" +
	"\vexit_status\"c\n" +
	"\x19TaskMountDirectoryRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\"l\n" +
	"\x1cTaskSnapshotDirectoryRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\tR\n" +
	"snapshotId\":\n" +
	"\x1dTaskSnapshotDirectoryResponse\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\"J\n" +
	"\x1bTaskUnmountDirectoryRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path*p\n" +
	"\x1aSandboxStdioFileDescriptor\x12(\n" +
	"$SANDBOX_STDIO_FILE_DESCRIPTOR_STDOUT\x10\x00\x12(\n" +
	"$SANDBOX_STDIO_FILE_DESCRIPTOR_STDERR\x10\x01*\x81\x01\n" +
	"\x14TaskExecStderrConfig\x12#\n" +
	"\x1fTASK_EXEC_STDERR_CONFIG_DEVNULL\x10\x00\x12 \n" +
	"\x1cTASK_EXEC_STDERR_CONFIG_PIPE\x10\x01\x12\"\n" +
	"\x1eTASK_EXEC_STDERR_CONFIG_STDOUT\x10\x02*u\n" +
	"\x1bTaskExecStdioFileDescriptor\x12*\n" +
	"&TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDOUT\x10\x00\x12*\n" +
	"&TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDERR\x10\x01*]\n" +
	"\x14TaskExecStdoutConfig\x12#\n" +
	"\x1fTASK_EXEC_STDOUT_CONFIG_DEVNULL\x10\x00\x12 \n" +
	"\x1cTASK_EXEC_STDOUT_CONFIG_PIPE\x10\x012\xea\x0e\n" +
	"\x11TaskCommandRouter\x12\x84\x01\n" +
	"\x13SandboxStdinWriteV2\x125.modal.task_command_router.SandboxStdinWriteV2Request\x1a6.modal.task_command_router.SandboxStdinWriteV2Response\x12\x83\x01\n" +
	"\x12SandboxStdioReadV2\x124.modal.task_command_router.SandboxStdioReadV2Request\x1a5.modal.task_command_router.SandboxStdioReadV2Response0\x01\x12\x84\x01\n" +
	"\x13TaskContainerCreate\x125.modal.task_command_router.TaskContainerCreateRequest\x1a6.modal.task_command_router.TaskContainerCreateResponse\x12{\n" +
	"\x10TaskContainerGet\x122.modal.task_command_router.TaskContainerGetRequest\x1a3.modal.task_command_router.TaskContainerGetResponse\x12~\n" +
	"\x11TaskContainerList\x123.modal.task_command_router.TaskContainerListRequest\x1a4.modal.task_command_router.TaskContainerListResponse\x12\x8d\x01\n" +
	"\x16TaskContainerTerminate\x128.modal.task_command_router.TaskContainerTerminateRequest\x1a9.modal.task_command_router.TaskContainerTerminateResponse\x12~\n" +
	"\x11TaskContainerWait\x123.modal.task_command_router.TaskContainerWaitRequest\x1a4.modal.task_command_router.TaskContainerWaitResponse\x12o\n" +
	"\fTaskExecPoll\x12..modal.task_command_router.TaskExecPollRequest\x1a/.modal.task_command_router.TaskExecPollResponse\x12r\n" +
	"\rTaskExecStart\x12/.modal.task_command_router.TaskExecStartRequest\x1a0.modal.task_command_router.TaskExecStartResponse\x12\x81\x01\n" +
	"\x12TaskExecStdinWrite\x124.modal.task_command_router.TaskExecStdinWriteRequest\x1a5.modal.task_command_router.TaskExecStdinWriteResponse\x12\x80\x01\n" +
	"\x11TaskExecStdioRead\x123.modal.task_command_router.TaskExecStdioReadRequest\x1a4.modal.task_command_router.TaskExecStdioReadResponse0\x01\x12o\n" +
	"\fTaskExecWait\x12..modal.task_command_router.TaskExecWaitRequest\x1a/.modal.task_command_router.TaskExecWaitResponse\x12b\n" +
	"\x12TaskMountDirectory\x124.modal.task_command_router.TaskMountDirectoryRequest\x1a\x16.google.protobuf.Empty\x12\x8a\x01\n" +
	"\x15TaskSnapshotDirectory\x127.modal.task_command_router.TaskSnapshotDirectoryRequest\x1a8.modal.task_command_router.TaskSnapshotDirectoryResponse\x12f\n" +
	"\x14TaskUnmountDirectory\x126.modal.task_command_router.TaskUnmountDirectoryRequest\x1a\x16.google.protobuf.EmptyB&Z$github.com/modal-labs/modal/go/protob\x06proto3"

var file_modal_proto_task_command_router_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_modal_proto_task_command_router_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_modal_proto_task_command_router_proto_goTypes = []any{
	(SandboxStdioFileDescriptor)(0),        // 0: modal.task_command_router.SandboxStdioFileDescriptor
	(TaskExecStderrConfig)(0),              // 1: modal.task_command_router.TaskExecStderrConfig
	(TaskExecStdioFileDescriptor)(0),       // 2: modal.task_command_router.TaskExecStdioFileDescriptor
	(TaskExecStdoutConfig)(0),              // 3: modal.task_command_router.TaskExecStdoutConfig
	(*SandboxStdinWriteV2Request)(nil),     // 4: modal.task_command_router.SandboxStdinWriteV2Request
	(*SandboxStdinWriteV2Response)(nil),    // 5: modal.task_command_router.SandboxStdinWriteV2Response
	(*SandboxStdioReadV2Request)(nil),      // 6: modal.task_command_router.SandboxStdioReadV2Request
	(*SandboxStdioReadV2Response)(nil),     // 7: modal.task_command_router.SandboxStdioReadV2Response
	(*TaskContainerCreateRequest)(nil),     // 8: modal.task_command_router.TaskContainerCreateRequest
	(*TaskContainerCreateResponse)(nil),    // 9: modal.task_command_router.TaskContainerCreateResponse
	(*TaskContainerGetRequest)(nil),        // 10: modal.task_command_router.TaskContainerGetRequest
	(*TaskContainerGetResponse)(nil),       // 11: modal.task_command_router.TaskContainerGetResponse
	(*TaskContainerInfo)(nil),              // 12: modal.task_command_router.TaskContainerInfo
	(*TaskContainerListRequest)(nil),       // 13: modal.task_command_router.TaskContainerListRequest
	(*TaskContainerListResponse)(nil),      // 14: modal.task_command_router.TaskContainerListResponse
	(*TaskContainerTerminateRequest)(nil),  // 15: modal.task_command_router.TaskContainerTerminateRequest
	(*TaskContainerTerminateResponse)(nil), // 16: modal.task_command_router.TaskContainerTerminateResponse
	(*TaskContainerWaitRequest)(nil),       // 17: modal.task_command_router.TaskContainerWaitRequest
	(*TaskContainerWaitResponse)(nil),      // 18: modal.task_command_router.TaskContainerWaitResponse
	(*TaskExecPollRequest)(nil),            // 19: modal.task_command_router.TaskExecPollRequest
	(*TaskExecPollResponse)(nil),           // 20: modal.task_command_router.TaskExecPollResponse
	(*TaskExecStartRequest)(nil),           // 21: modal.task_command_router.TaskExecStartRequest
	(*TaskExecStartResponse)(nil),          // 22: modal.task_command_router.TaskExecStartResponse
	(*TaskExecStdinWriteRequest)(nil),      // 23: modal.task_command_router.TaskExecStdinWriteRequest
	(*TaskExecStdinWriteResponse)(nil),     // 24: modal.task_command_router.TaskExecStdinWriteResponse
	(*TaskExecStdioReadRequest)(nil),       // 25: modal.task_command_router.TaskExecStdioReadRequest
	(*TaskExecStdioReadResponse)(nil),      // 26: modal.task_command_router.TaskExecStdioReadResponse
	(*TaskExecWaitRequest)(nil),            // 27: modal.task_command_router.TaskExecWaitRequest
	(*TaskExecWaitResponse)(nil),           // 28: modal.task_command_router.TaskExecWaitResponse
	(*TaskMountDirectoryRequest)(nil),      // 29: modal.task_command_router.TaskMountDirectoryRequest
	(*TaskSnapshotDirectoryRequest)(nil),   // 30: modal.task_command_router.TaskSnapshotDirectoryRequest
	(*TaskSnapshotDirectoryResponse)(nil),  // 31: modal.task_command_router.TaskSnapshotDirectoryResponse
	(*TaskUnmountDirectoryRequest)(nil),    // 32: modal.task_command_router.TaskUnmountDirectoryRequest
	nil,                                    // 33: modal.task_command_router.TaskContainerCreateRequest.EnvEntry
	nil,                                    // 34: modal.task_command_router.TaskExecStartRequest.EnvEntry
	(*GenericResult)(nil),                  // 35: modal.client.GenericResult
	(*PTYInfo)(nil),                        // 36: modal.client.PTYInfo
	(*emptypb.Empty)(nil),                  // 37: google.protobuf.Empty
}
var file_modal_proto_task_command_router_proto_depIdxs = []int32{
	0,  // 0: modal.task_command_router.SandboxStdioReadV2Request.file_descriptor:type_name -> modal.task_command_router.SandboxStdioFileDescriptor
	33, // 1: modal.task_command_router.TaskContainerCreateRequest.env:type_name -> modal.task_command_router.TaskContainerCreateRequest.EnvEntry
	12, // 2: modal.task_command_router.TaskContainerGetResponse.container:type_name -> modal.task_command_router.TaskContainerInfo
	35, // 3: modal.task_command_router.TaskContainerInfo.result:type_name -> modal.client.GenericResult
	12, // 4: modal.task_command_router.TaskContainerListResponse.containers:type_name -> modal.task_command_router.TaskContainerInfo
	35, // 5: modal.task_command_router.TaskContainerWaitResponse.result:type_name -> modal.client.GenericResult
	3,  // 6: modal.task_command_router.TaskExecStartRequest.stdout_config:type_name -> modal.task_command_router.TaskExecStdoutConfig
	1,  // 7: modal.task_command_router.TaskExecStartRequest.stderr_config:type_name -> modal.task_command_router.TaskExecStderrConfig
	36, // 8: modal.task_command_router.TaskExecStartRequest.pty_info:type_name -> modal.client.PTYInfo
	34, // 9: modal.task_command_router.TaskExecStartRequest.env:type_name -> modal.task_command_router.TaskExecStartRequest.EnvEntry
	2,  // 10: modal.task_command_router.TaskExecStdioReadRequest.file_descriptor:type_name -> modal.task_command_router.TaskExecStdioFileDescriptor
	4,  // 11: modal.task_command_router.TaskCommandRouter.SandboxStdinWriteV2:input_type -> modal.task_command_router.SandboxStdinWriteV2Request
	6,  // 12: modal.task_command_router.TaskCommandRouter.SandboxStdioReadV2:input_type -> modal.task_command_router.SandboxStdioReadV2Request
	8,  // 13: modal.task_command_router.TaskCommandRouter.TaskContainerCreate:input_type -> modal.task_command_router.TaskContainerCreateRequest
	10, // 14: modal.task_command_router.TaskCommandRouter.TaskContainerGet:input_type -> modal.task_command_router.TaskContainerGetRequest
	13, // 15: modal.task_command_router.TaskCommandRouter.TaskContainerList:input_type -> modal.task_command_router.TaskContainerListRequest
	15, // 16: modal.task_command_router.TaskCommandRouter.TaskContainerTerminate:input_type -> modal.task_command_router.TaskContainerTerminateRequest
	17, // 17: modal.task_command_router.TaskCommandRouter.TaskContainerWait:input_type -> modal.task_command_router.TaskContainerWaitRequest
	19, // 18: modal.task_command_router.TaskCommandRouter.TaskExecPoll:input_type -> modal.task_command_router.TaskExecPollRequest
	21, // 19: modal.task_command_router.TaskCommandRouter.TaskExecStart:input_type -> modal.task_command_router.TaskExecStartRequest
	23, // 20: modal.task_command_router.TaskCommandRouter.TaskExecStdinWrite:input_type -> modal.task_command_router.TaskExecStdinWriteRequest
	25, // 21: modal.task_command_router.TaskCommandRouter.TaskExecStdioRead:input_type -> modal.task_command_router.TaskExecStdioReadRequest
	27, // 22: modal.task_command_router.TaskCommandRouter.TaskExecWait:input_type -> modal.task_command_router.TaskExecWaitRequest
	29, // 23: modal.task_command_router.TaskCommandRouter.TaskMountDirectory:input_type -> modal.task_command_router.TaskMountDirectoryRequest
	30, // 24: modal.task_command_router.TaskCommandRouter.TaskSnapshotDirectory:input_type -> modal.task_command_router.TaskSnapshotDirectoryRequest
	32, // 25: modal.task_command_router.TaskCommandRouter.TaskUnmountDirectory:input_type -> modal.task_command_router.TaskUnmountDirectoryRequest
	5,  // 26: modal.task_command_router.TaskCommandRouter.SandboxStdinWriteV2:output_type -> modal.task_command_router.SandboxStdinWriteV2Response
	7,  // 27: modal.task_command_router.TaskCommandRouter.SandboxStdioReadV2:output_type -> modal.task_command_router.SandboxStdioReadV2Response
	9,  // 28: modal.task_command_router.TaskCommandRouter.TaskContainerCreate:output_type -> modal.task_command_router.TaskContainerCreateResponse
	11, // 29: modal.task_command_router.TaskCommandRouter.TaskContainerGet:output_type -> modal.task_command_router.TaskContainerGetResponse
	14, // 30: modal.task_command_router.TaskCommandRouter.TaskContainerList:output_type -> modal.task_command_router.TaskContainerListResponse
	16, // 31: modal.task_command_router.TaskCommandRouter.TaskContainerTerminate:output_type -> modal.task_command_router.TaskContainerTerminateResponse
	18, // 32: modal.task_command_router.TaskCommandRouter.TaskContainerWait:output_type -> modal.task_command_router.TaskContainerWaitResponse
	20, // 33: modal.task_command_router.TaskCommandRouter.TaskExecPoll:output_type -> modal.task_command_router.TaskExecPollResponse
	22, // 34: modal.task_command_router.TaskCommandRouter.TaskExecStart:output_type -> modal.task_command_router.TaskExecStartResponse
	24, // 35: modal.task_command_router.TaskCommandRouter.TaskExecStdinWrite:output_type -> modal.task_command_router.TaskExecStdinWriteResponse
	26, // 36: modal.task_command_router.TaskCommandRouter.TaskExecStdioRead:output_type -> modal.task_command_router.TaskExecStdioReadResponse
	28, // 37: modal.task_command_router.TaskCommandRouter.TaskExecWait:output_type -> modal.task_command_router.TaskExecWaitResponse
	37, // 38: modal.task_command_router.TaskCommandRouter.TaskMountDirectory:output_type -> google.protobuf.Empty
	31, // 39: modal.task_command_router.TaskCommandRouter.TaskSnapshotDirectory:output_type -> modal.task_command_router.TaskSnapshotDirectoryResponse
	37, // 40: modal.task_command_router.TaskCommandRouter.TaskUnmountDirectory:output_type -> google.protobuf.Empty
	26, // [26:41] is the sub-list for method output_type
	11, // [11:26] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_modal_proto_task_command_router_proto_init() }
func file_modal_proto_task_command_router_proto_init() {
	if File_modal_proto_task_command_router_proto != nil {
		return
	}
	file_modal_proto_api_proto_init()
	file_modal_proto_task_command_router_proto_msgTypes[16].OneofWrappers = []any{
		(*taskExecPollResponse_Code)(nil),
		(*taskExecPollResponse_Signal)(nil),
	}
	file_modal_proto_task_command_router_proto_msgTypes[17].OneofWrappers = []any{}
	file_modal_proto_task_command_router_proto_msgTypes[24].OneofWrappers = []any{
		(*taskExecWaitResponse_Code)(nil),
		(*taskExecWaitResponse_Signal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modal_proto_task_command_router_proto_rawDesc), len(file_modal_proto_task_command_router_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modal_proto_task_command_router_proto_goTypes,
		DependencyIndexes: file_modal_proto_task_command_router_proto_depIdxs,
		EnumInfos:         file_modal_proto_task_command_router_proto_enumTypes,
		MessageInfos:      file_modal_proto_task_command_router_proto_msgTypes,
	}.Build()
	File_modal_proto_task_command_router_proto = out.File
	file_modal_proto_task_command_router_proto_goTypes = nil
	file_modal_proto_task_command_router_proto_depIdxs = nil
}
