name: setup-cached-python

inputs:
  version:
    description: Which Python version to install
    required: true
    default: "3.9"

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
      with:
        python-version: ${{ inputs.version }}

    - name: Enable caching
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      with:
        enable-cache: true
        uv-version: "0.9.7"

    - name: Install Python packages
      shell: bash
      run: |
        uv pip install -r requirements.dev.txt
      env:
        UV_SYSTEM_PYTHON: 1
