name: setup-cached-python

inputs:
  python-version:
    description: Which Python version to install
    required: true
    default: "3.9"
  use-conda:
    description: Whether to use Conda
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install Python
      if: ${{ inputs.use-conda == 'false' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Conda
      if: ${{ inputs.use-conda == 'true' }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get cached python dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: |
          ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('**/setup.cfg', 'requirements.dev.txt') }}
        restore-keys: ${{ runner.os }}-${{ env.pythonLocation }}-

    - name: Install Python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt
