name: Client Unit tests
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
    secrets:
      MODAL_TOKEN_ID:
        required: true
      MODAL_TOKEN_SECRET:
        required: true

env:
  UV_FROZEN: 1
  TERM: linux
  TERMINFO: /etc/terminfo
  PYTHONIOENCODING: utf-8

jobs:
  client-test:
    name: Unit tests on ${{ matrix.python-version }} and ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false # run all variants across python versions/os to completion
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: ["ubuntu-24.04"]
        include:
          - os: "macos-15-intel" # x86-64
            python-version: "3.10"
          - os: "macos-15" # ARM64 (M1)
            python-version: "3.10"
          - os: "windows-latest"
            python-version: "3.10"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./.github/actions/setup-cached-python-client
        with:
          version: ${{ matrix.python-version }}
          working-directory: ${{ inputs.working-directory }}
          no-build-isolation:
            ${{ matrix.os == 'macos-15' && 'true' || 'false' }}

      - name: Build protobuf
        run: inv protoc

      - name: Run client tests
        run: inv test

      - name: Run docstring tests
        if: github.event.pull_request.head.repo.fork == false
        env:
          MODAL_ENVIRONMENT: client-doc-tests
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
        run: pytest -v --markdown-docs -m markdown-docs modal

  container-dependencies:
    name:
      Check minimal container dependencies for ${{ matrix.python-version }} -
      ${{ matrix.image-builder-version }}
    runs-on: ubuntu-24.04
    timeout-minutes: 4
    strategy:
      matrix:
        include:
          - image-builder-version: "2024.04"
            python-version: "3.10"
          - image-builder-version: "2024.04"
            python-version: "3.12"
          - image-builder-version: "2024.10"
            python-version: "3.10"
          - image-builder-version: "2024.10"
            python-version: "3.13"
          - image-builder-version: "2025.06"
            python-version: "3.10"
          - image-builder-version: "2025.06"
            python-version: "3.14"

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r modal/builder/${{ matrix.image-builder-version }}.txt
          pip install synchronicity

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          version: "0.10.9"

      - name: Compile protos
        run:
          uv run --python ${{ matrix.python-version }} --with-requirements
          requirements.protos.txt compile_protos.py --skip-mypy

      - name: Check entrypoint import
        run: |
          python -c 'import modal._container_entrypoint; import modal._runtime.asgi'
          if [ "${{ matrix.image-builder-version }}" == "2024.04" ]; then python -c 'import fastapi'; fi
