name: Client Check

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      python-version:
        type: string
        default: "3.10"

jobs:
  lint:
    name: Ruff linting
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./.github/actions/setup-cached-python-client
        with:
          version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.working-directory }}

      - run: inv lint

      - run: inv lint-protos

      - run: inv lint-changelog

  type-check:
    name: Static type checks
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./.github/actions/setup-cached-python-client
        with:
          version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.working-directory }}

      - run: inv protoc

      - name: Build type stubs
        run: inv type-stubs

      - run: inv type-check

  check-copyright:
    name: Check copyright
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./.github/actions/setup-cached-python-client
        with:
          version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.working-directory }}

      - run: inv check-copyright
