name: Client Docs

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      python-version:
        type: string
        default: "3.10"

jobs:
  doc-test:
    name: Doc generation tests
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./.github/actions/setup-cached-python-client
        with:
          version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.working-directory }}

      - name: Build protobuf
        run: inv protoc

      - name: Generate reference docs
        run: python -m modal_docs.gen_reference_docs reference_docs_output

      - name: Generate CLI docs
        run: python -m modal_docs.gen_cli_docs cli_docs
